<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 6 Logistic Regression | Beyond Multiple Linear Regression</title>
  <meta name="description" content="An applied textbook on generalized linear models and multilevel models for advanced undergraduates, featuring many real, unique data sets. It is intended to be accessible to undergraduate students who have successfully completed a regression course. Even though there is no mathematical prerequisite, we still introduce fairly sophisticated topics such as likelihood theory, zero-inflated Poisson, and parametric bootstrapping in an intuitive and applied manner. We believe strongly in case studies featuring real data and real research questions; thus, most of the data in the textbook arises from collaborative research conducted by the authors and their students, or from student projects. Our goal is that, after working through this material, students will develop an expanded toolkit and a greater appreciation for the wider world of data and statistical modeling." />
  <meta name="generator" content="bookdown 0.19 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 6 Logistic Regression | Beyond Multiple Linear Regression" />
  <meta property="og:type" content="book" />
  
  <meta property="og:image" content="data/book_cover.jpg" />
  <meta property="og:description" content="An applied textbook on generalized linear models and multilevel models for advanced undergraduates, featuring many real, unique data sets. It is intended to be accessible to undergraduate students who have successfully completed a regression course. Even though there is no mathematical prerequisite, we still introduce fairly sophisticated topics such as likelihood theory, zero-inflated Poisson, and parametric bootstrapping in an intuitive and applied manner. We believe strongly in case studies featuring real data and real research questions; thus, most of the data in the textbook arises from collaborative research conducted by the authors and their students, or from student projects. Our goal is that, after working through this material, students will develop an expanded toolkit and a greater appreciation for the wider world of data and statistical modeling." />
  <meta name="github-repo" content="proback/BeyondMLR" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 6 Logistic Regression | Beyond Multiple Linear Regression" />
  
  <meta name="twitter:description" content="An applied textbook on generalized linear models and multilevel models for advanced undergraduates, featuring many real, unique data sets. It is intended to be accessible to undergraduate students who have successfully completed a regression course. Even though there is no mathematical prerequisite, we still introduce fairly sophisticated topics such as likelihood theory, zero-inflated Poisson, and parametric bootstrapping in an intuitive and applied manner. We believe strongly in case studies featuring real data and real research questions; thus, most of the data in the textbook arises from collaborative research conducted by the authors and their students, or from student projects. Our goal is that, after working through this material, students will develop an expanded toolkit and a greater appreciation for the wider world of data and statistical modeling." />
  <meta name="twitter:image" content="data/book_cover.jpg" />

<meta name="author" content="Paul Roback and Julie Legler" />


<meta name="date" content="2021-01-12" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="ch-glms.html"/>
<link rel="next" href="ch-corrdata.html"/>
<script src="libs/jquery/jquery.min.js"></script>
<link href="libs/gitbook/css/style.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block/empty-anchor.js"></script>
<script src="libs/kePrint/kePrint.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="css\style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Beyond Multiple Linear Regression</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#copyright"><i class="fa fa-check"></i>Copyright</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#about-the-authors"><i class="fa fa-check"></i>About the Authors</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#dedication"><i class="fa fa-check"></i>Dedication</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="ch-MLRreview.html"><a href="ch-MLRreview.html"><i class="fa fa-check"></i><b>1</b> Review of Multiple Linear Regression</a><ul>
<li class="chapter" data-level="1.1" data-path="ch-MLRreview.html"><a href="ch-MLRreview.html#learning-objectives"><i class="fa fa-check"></i><b>1.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="1.2" data-path="ch-MLRreview.html"><a href="ch-MLRreview.html#introduction-to-beyond-multiple-linear-regression"><i class="fa fa-check"></i><b>1.2</b> Introduction to Beyond Multiple Linear Regression</a></li>
<li class="chapter" data-level="1.3" data-path="ch-MLRreview.html"><a href="ch-MLRreview.html#assumptions-for-linear-least-squares-regression"><i class="fa fa-check"></i><b>1.3</b> Assumptions for Linear Least Squares Regression</a><ul>
<li class="chapter" data-level="1.3.1" data-path="ch-MLRreview.html"><a href="ch-MLRreview.html#cases-without-assumption-violations"><i class="fa fa-check"></i><b>1.3.1</b> Cases Without Assumption Violations</a></li>
<li class="chapter" data-level="1.3.2" data-path="ch-MLRreview.html"><a href="ch-MLRreview.html#cases-with-assumption-violations"><i class="fa fa-check"></i><b>1.3.2</b> Cases With Assumption Violations</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="ch-MLRreview.html"><a href="ch-MLRreview.html#review-of-multiple-linear-regression"><i class="fa fa-check"></i><b>1.4</b> Review of Multiple Linear Regression</a><ul>
<li class="chapter" data-level="1.4.1" data-path="ch-MLRreview.html"><a href="ch-MLRreview.html#cs:derby"><i class="fa fa-check"></i><b>1.4.1</b> Case Study: Kentucky Derby</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="ch-MLRreview.html"><a href="ch-MLRreview.html#explorech1"><i class="fa fa-check"></i><b>1.5</b> Initial Exploratory Analyses</a><ul>
<li class="chapter" data-level="1.5.1" data-path="ch-MLRreview.html"><a href="ch-MLRreview.html#data-organization"><i class="fa fa-check"></i><b>1.5.1</b> Data Organization</a></li>
<li class="chapter" data-level="1.5.2" data-path="ch-MLRreview.html"><a href="ch-MLRreview.html#univariate-summaries"><i class="fa fa-check"></i><b>1.5.2</b> Univariate Summaries</a></li>
<li class="chapter" data-level="1.5.3" data-path="ch-MLRreview.html"><a href="ch-MLRreview.html#bivariate-summaries"><i class="fa fa-check"></i><b>1.5.3</b> Bivariate Summaries</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="ch-MLRreview.html"><a href="ch-MLRreview.html#multreg"><i class="fa fa-check"></i><b>1.6</b> Multiple Linear Regression Modeling</a><ul>
<li class="chapter" data-level="1.6.1" data-path="ch-MLRreview.html"><a href="ch-MLRreview.html#SLRcontinuous"><i class="fa fa-check"></i><b>1.6.1</b> Simple Linear Regression with a Continuous Predictor</a></li>
<li class="chapter" data-level="1.6.2" data-path="ch-MLRreview.html"><a href="ch-MLRreview.html#linear-regression-with-a-binary-predictor"><i class="fa fa-check"></i><b>1.6.2</b> Linear Regression with a Binary Predictor</a></li>
<li class="chapter" data-level="1.6.3" data-path="ch-MLRreview.html"><a href="ch-MLRreview.html#multiple-linear-regression-with-two-predictors"><i class="fa fa-check"></i><b>1.6.3</b> Multiple Linear Regression with Two Predictors</a></li>
<li class="chapter" data-level="1.6.4" data-path="ch-MLRreview.html"><a href="ch-MLRreview.html#multreg-inference"><i class="fa fa-check"></i><b>1.6.4</b> Inference in Multiple Linear Regression: Normal Theory</a></li>
<li class="chapter" data-level="1.6.5" data-path="ch-MLRreview.html"><a href="ch-MLRreview.html#multreg-boot"><i class="fa fa-check"></i><b>1.6.5</b> Inference in Multiple Linear Regression: Bootstrapping</a></li>
<li class="chapter" data-level="1.6.6" data-path="ch-MLRreview.html"><a href="ch-MLRreview.html#multiple-linear-regression-with-an-interaction-term"><i class="fa fa-check"></i><b>1.6.6</b> Multiple Linear Regression with an Interaction Term</a></li>
<li class="chapter" data-level="1.6.7" data-path="ch-MLRreview.html"><a href="ch-MLRreview.html#multreg_build"><i class="fa fa-check"></i><b>1.6.7</b> Building a Multiple Linear Regression Model</a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path="ch-MLRreview.html"><a href="ch-MLRreview.html#preview-of-remaining-chapters"><i class="fa fa-check"></i><b>1.7</b> Preview of Remaining Chapters</a><ul>
<li class="chapter" data-level="1.7.1" data-path="ch-MLRreview.html"><a href="ch-MLRreview.html#soccer"><i class="fa fa-check"></i><b>1.7.1</b> Soccer</a></li>
<li class="chapter" data-level="1.7.2" data-path="ch-MLRreview.html"><a href="ch-MLRreview.html#elephant-mating"><i class="fa fa-check"></i><b>1.7.2</b> Elephant Mating</a></li>
<li class="chapter" data-level="1.7.3" data-path="ch-MLRreview.html"><a href="ch-MLRreview.html#parenting-and-gang-activity"><i class="fa fa-check"></i><b>1.7.3</b> Parenting and Gang Activity</a></li>
<li class="chapter" data-level="1.7.4" data-path="ch-MLRreview.html"><a href="ch-MLRreview.html#crime"><i class="fa fa-check"></i><b>1.7.4</b> Crime</a></li>
</ul></li>
<li class="chapter" data-level="1.8" data-path="ch-MLRreview.html"><a href="ch-MLRreview.html#exercises"><i class="fa fa-check"></i><b>1.8</b> Exercises</a><ul>
<li class="chapter" data-level="1.8.1" data-path="ch-MLRreview.html"><a href="ch-MLRreview.html#conceptual-exercises"><i class="fa fa-check"></i><b>1.8.1</b> Conceptual Exercises</a></li>
<li class="chapter" data-level="1.8.2" data-path="ch-MLRreview.html"><a href="ch-MLRreview.html#guided-exercises"><i class="fa fa-check"></i><b>1.8.2</b> Guided Exercises</a></li>
<li class="chapter" data-level="1.8.3" data-path="ch-MLRreview.html"><a href="ch-MLRreview.html#open-ended-exercises"><i class="fa fa-check"></i><b>1.8.3</b> Open-Ended Exercises</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="ch-beyondmost.html"><a href="ch-beyondmost.html"><i class="fa fa-check"></i><b>2</b> Beyond Least Squares: Using Likelihoods</a><ul>
<li class="chapter" data-level="2.1" data-path="ch-beyondmost.html"><a href="ch-beyondmost.html#learning-objectives-1"><i class="fa fa-check"></i><b>2.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="2.2" data-path="ch-beyondmost.html"><a href="ch-beyondmost.html#case-study-does-sex-run-in-families"><i class="fa fa-check"></i><b>2.2</b> Case Study: Does Sex Run in Families?</a><ul>
<li class="chapter" data-level="2.2.1" data-path="ch-beyondmost.html"><a href="ch-beyondmost.html#research-questions"><i class="fa fa-check"></i><b>2.2.1</b> Research Questions</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="ch-beyondmost.html"><a href="ch-beyondmost.html#model-0-sex-unconditional-equal-probabilities"><i class="fa fa-check"></i><b>2.3</b> Model 0: Sex Unconditional, Equal Probabilities</a></li>
<li class="chapter" data-level="2.4" data-path="ch-beyondmost.html"><a href="ch-beyondmost.html#sex_unconditional_model"><i class="fa fa-check"></i><b>2.4</b> Model 1: Sex Unconditional, Unequal Probabilities</a><ul>
<li class="chapter" data-level="2.4.1" data-path="ch-beyondmost.html"><a href="ch-beyondmost.html#what-is-a-likelihood"><i class="fa fa-check"></i><b>2.4.1</b> What Is a Likelihood?</a></li>
<li class="chapter" data-level="2.4.2" data-path="ch-beyondmost.html"><a href="ch-beyondmost.html#findMLE.sec"><i class="fa fa-check"></i><b>2.4.2</b> Finding MLEs</a></li>
<li class="chapter" data-level="2.4.3" data-path="ch-beyondmost.html"><a href="ch-beyondmost.html#summary"><i class="fa fa-check"></i><b>2.4.3</b> Summary</a></li>
<li class="chapter" data-level="2.4.4" data-path="ch-beyondmost.html"><a href="ch-beyondmost.html#is-a-likelihood-a-probability-function-optional"><i class="fa fa-check"></i><b>2.4.4</b> Is a Likelihood a Probability Function? (optional)</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="ch-beyondmost.html"><a href="ch-beyondmost.html#sex_conditional.sec"><i class="fa fa-check"></i><b>2.5</b> Model 2: Sex Conditional</a><ul>
<li class="chapter" data-level="2.5.1" data-path="ch-beyondmost.html"><a href="ch-beyondmost.html#model-specification"><i class="fa fa-check"></i><b>2.5.1</b> Model Specification</a></li>
<li class="chapter" data-level="2.5.2" data-path="ch-beyondmost.html"><a href="ch-beyondmost.html#application-to-hypothetical-data"><i class="fa fa-check"></i><b>2.5.2</b> Application to Hypothetical Data</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="ch-beyondmost.html"><a href="ch-beyondmost.html#case-study-analysis-of-the-nlsy-data"><i class="fa fa-check"></i><b>2.6</b> Case Study: Analysis of the NLSY Data</a><ul>
<li class="chapter" data-level="2.6.1" data-path="ch-beyondmost.html"><a href="ch-beyondmost.html#model-building-plan"><i class="fa fa-check"></i><b>2.6.1</b> Model Building Plan</a></li>
<li class="chapter" data-level="2.6.2" data-path="ch-beyondmost.html"><a href="ch-beyondmost.html#EDA.sec"><i class="fa fa-check"></i><b>2.6.2</b> Exploratory Data Analysis</a></li>
<li class="chapter" data-level="2.6.3" data-path="ch-beyondmost.html"><a href="ch-beyondmost.html#likelihood-for-the-sex-unconditional-model"><i class="fa fa-check"></i><b>2.6.3</b> Likelihood for the Sex Unconditional Model</a></li>
<li class="chapter" data-level="2.6.4" data-path="ch-beyondmost.html"><a href="ch-beyondmost.html#sex-cond-lik"><i class="fa fa-check"></i><b>2.6.4</b> Likelihood for the Sex Conditional Model</a></li>
<li class="chapter" data-level="2.6.5" data-path="ch-beyondmost.html"><a href="ch-beyondmost.html#sec-lrtest"><i class="fa fa-check"></i><b>2.6.5</b> Model Comparisons</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="ch-beyondmost.html"><a href="ch-beyondmost.html#model-3-stopping-rule-model-waiting-for-a-boy"><i class="fa fa-check"></i><b>2.7</b> Model 3: Stopping Rule Model (waiting for a boy)</a><ul>
<li class="chapter" data-level="2.7.1" data-path="ch-beyondmost.html"><a href="ch-beyondmost.html#non-nested-models"><i class="fa fa-check"></i><b>2.7.1</b> Non-nested Models</a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="ch-beyondmost.html"><a href="ch-beyondmost.html#summary-of-model-building"><i class="fa fa-check"></i><b>2.8</b> Summary of Model Building</a></li>
<li class="chapter" data-level="2.9" data-path="ch-beyondmost.html"><a href="ch-beyondmost.html#likelihood-based-methods"><i class="fa fa-check"></i><b>2.9</b> Likelihood-Based Methods</a></li>
<li class="chapter" data-level="2.10" data-path="ch-beyondmost.html"><a href="ch-beyondmost.html#likelihoods-and-this-course"><i class="fa fa-check"></i><b>2.10</b> Likelihoods and This Course</a></li>
<li class="chapter" data-level="2.11" data-path="ch-beyondmost.html"><a href="ch-beyondmost.html#exercises-1"><i class="fa fa-check"></i><b>2.11</b> Exercises</a><ul>
<li class="chapter" data-level="2.11.1" data-path="ch-beyondmost.html"><a href="ch-beyondmost.html#conceptual-exercises-1"><i class="fa fa-check"></i><b>2.11.1</b> Conceptual Exercises</a></li>
<li class="chapter" data-level="2.11.2" data-path="ch-beyondmost.html"><a href="ch-beyondmost.html#guided-exercises-1"><i class="fa fa-check"></i><b>2.11.2</b> Guided Exercises</a></li>
<li class="chapter" data-level="2.11.3" data-path="ch-beyondmost.html"><a href="ch-beyondmost.html#open-ended-exercises-1"><i class="fa fa-check"></i><b>2.11.3</b> Open-Ended Exercises</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="ch-distthry.html"><a href="ch-distthry.html"><i class="fa fa-check"></i><b>3</b> Distribution Theory</a><ul>
<li class="chapter" data-level="3.1" data-path="ch-distthry.html"><a href="ch-distthry.html#learning-objectives-2"><i class="fa fa-check"></i><b>3.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="3.2" data-path="ch-distthry.html"><a href="ch-distthry.html#introduction"><i class="fa fa-check"></i><b>3.2</b> Introduction</a></li>
<li class="chapter" data-level="3.3" data-path="ch-distthry.html"><a href="ch-distthry.html#discrete-random-variables"><i class="fa fa-check"></i><b>3.3</b> Discrete Random Variables</a><ul>
<li class="chapter" data-level="3.3.1" data-path="ch-distthry.html"><a href="ch-distthry.html#sec-binary"><i class="fa fa-check"></i><b>3.3.1</b> Binary Random Variable</a></li>
<li class="chapter" data-level="3.3.2" data-path="ch-distthry.html"><a href="ch-distthry.html#sec-binomial"><i class="fa fa-check"></i><b>3.3.2</b> Binomial Random Variable</a></li>
<li class="chapter" data-level="3.3.3" data-path="ch-distthry.html"><a href="ch-distthry.html#geometric-random-variable"><i class="fa fa-check"></i><b>3.3.3</b> Geometric Random Variable</a></li>
<li class="chapter" data-level="3.3.4" data-path="ch-distthry.html"><a href="ch-distthry.html#negative-binomial-random-variable"><i class="fa fa-check"></i><b>3.3.4</b> Negative Binomial Random Variable</a></li>
<li class="chapter" data-level="3.3.5" data-path="ch-distthry.html"><a href="ch-distthry.html#hypergeometric-random-variable"><i class="fa fa-check"></i><b>3.3.5</b> Hypergeometric Random Variable</a></li>
<li class="chapter" data-level="3.3.6" data-path="ch-distthry.html"><a href="ch-distthry.html#poisson-random-variable"><i class="fa fa-check"></i><b>3.3.6</b> Poisson Random Variable</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="ch-distthry.html"><a href="ch-distthry.html#continuous-random-variables"><i class="fa fa-check"></i><b>3.4</b> Continuous Random Variables</a><ul>
<li class="chapter" data-level="3.4.1" data-path="ch-distthry.html"><a href="ch-distthry.html#exponential-random-variable"><i class="fa fa-check"></i><b>3.4.1</b> Exponential Random Variable</a></li>
<li class="chapter" data-level="3.4.2" data-path="ch-distthry.html"><a href="ch-distthry.html#gamma-random-variable"><i class="fa fa-check"></i><b>3.4.2</b> Gamma Random Variable</a></li>
<li class="chapter" data-level="3.4.3" data-path="ch-distthry.html"><a href="ch-distthry.html#normal-gaussian-random-variable"><i class="fa fa-check"></i><b>3.4.3</b> Normal (Gaussian) Random Variable</a></li>
<li class="chapter" data-level="3.4.4" data-path="ch-distthry.html"><a href="ch-distthry.html#beta-random-variable"><i class="fa fa-check"></i><b>3.4.4</b> Beta Random Variable</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="ch-distthry.html"><a href="ch-distthry.html#distributions-used-in-testing"><i class="fa fa-check"></i><b>3.5</b> Distributions Used in Testing</a><ul>
<li class="chapter" data-level="3.5.1" data-path="ch-distthry.html"><a href="ch-distthry.html#chi2-distribution"><i class="fa fa-check"></i><b>3.5.1</b> <span class="math inline">\(\chi^2\)</span> Distribution</a></li>
<li class="chapter" data-level="3.5.2" data-path="ch-distthry.html"><a href="ch-distthry.html#students-t-distribution"><i class="fa fa-check"></i><b>3.5.2</b> Student’s <span class="math inline">\(t\)</span>-Distribution</a></li>
<li class="chapter" data-level="3.5.3" data-path="ch-distthry.html"><a href="ch-distthry.html#f-distribution"><i class="fa fa-check"></i><b>3.5.3</b> <span class="math inline">\(F\)</span>-Distribution</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="ch-distthry.html"><a href="ch-distthry.html#additional-resources"><i class="fa fa-check"></i><b>3.6</b> Additional Resources</a></li>
<li class="chapter" data-level="3.7" data-path="ch-distthry.html"><a href="ch-distthry.html#exercises-2"><i class="fa fa-check"></i><b>3.7</b> Exercises</a><ul>
<li class="chapter" data-level="3.7.1" data-path="ch-distthry.html"><a href="ch-distthry.html#conceptual-exercises-2"><i class="fa fa-check"></i><b>3.7.1</b> Conceptual Exercises</a></li>
<li class="chapter" data-level="3.7.2" data-path="ch-distthry.html"><a href="ch-distthry.html#guided-exercises-2"><i class="fa fa-check"></i><b>3.7.2</b> Guided Exercises</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="ch-poissonreg.html"><a href="ch-poissonreg.html"><i class="fa fa-check"></i><b>4</b> Poisson Regression</a><ul>
<li class="chapter" data-level="4.1" data-path="ch-poissonreg.html"><a href="ch-poissonreg.html#learning-objectives-3"><i class="fa fa-check"></i><b>4.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="4.2" data-path="ch-poissonreg.html"><a href="ch-poissonreg.html#introduction-to-poisson-regression"><i class="fa fa-check"></i><b>4.2</b> Introduction to Poisson Regression</a><ul>
<li class="chapter" data-level="4.2.1" data-path="ch-poissonreg.html"><a href="ch-poissonreg.html#poisson-regression-assumptions"><i class="fa fa-check"></i><b>4.2.1</b> Poisson Regression Assumptions</a></li>
<li class="chapter" data-level="4.2.2" data-path="ch-poissonreg.html"><a href="ch-poissonreg.html#a-graphical-look-at-poisson-regression"><i class="fa fa-check"></i><b>4.2.2</b> A Graphical Look at Poisson Regression</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="ch-poissonreg.html"><a href="ch-poissonreg.html#case-studies-overview"><i class="fa fa-check"></i><b>4.3</b> Case Studies Overview</a></li>
<li class="chapter" data-level="4.4" data-path="ch-poissonreg.html"><a href="ch-poissonreg.html#cs-philippines"><i class="fa fa-check"></i><b>4.4</b> Case Study: Household Size in the Philippines</a><ul>
<li class="chapter" data-level="4.4.1" data-path="ch-poissonreg.html"><a href="ch-poissonreg.html#organizedata4"><i class="fa fa-check"></i><b>4.4.1</b> Data Organization</a></li>
<li class="chapter" data-level="4.4.2" data-path="ch-poissonreg.html"><a href="ch-poissonreg.html#exploreHH"><i class="fa fa-check"></i><b>4.4.2</b> Exploratory Data Analyses</a></li>
<li class="chapter" data-level="4.4.3" data-path="ch-poissonreg.html"><a href="ch-poissonreg.html#sec-PoisInference"><i class="fa fa-check"></i><b>4.4.3</b> Estimation and Inference</a></li>
<li class="chapter" data-level="4.4.4" data-path="ch-poissonreg.html"><a href="ch-poissonreg.html#sec-Devtocompare"><i class="fa fa-check"></i><b>4.4.4</b> Using Deviances to Compare Models</a></li>
<li class="chapter" data-level="4.4.5" data-path="ch-poissonreg.html"><a href="ch-poissonreg.html#likelihood.sec"><i class="fa fa-check"></i><b>4.4.5</b> Using Likelihoods to Fit Models (optional)</a></li>
<li class="chapter" data-level="4.4.6" data-path="ch-poissonreg.html"><a href="ch-poissonreg.html#second-order-model"><i class="fa fa-check"></i><b>4.4.6</b> Second Order Model</a></li>
<li class="chapter" data-level="4.4.7" data-path="ch-poissonreg.html"><a href="ch-poissonreg.html#adding-a-covariate"><i class="fa fa-check"></i><b>4.4.7</b> Adding a Covariate</a></li>
<li class="chapter" data-level="4.4.8" data-path="ch-poissonreg.html"><a href="ch-poissonreg.html#sec-PoisResid"><i class="fa fa-check"></i><b>4.4.8</b> Residuals for Poisson Models (optional)</a></li>
<li class="chapter" data-level="4.4.9" data-path="ch-poissonreg.html"><a href="ch-poissonreg.html#sec-PoisGOF"><i class="fa fa-check"></i><b>4.4.9</b> Goodness-of-Fit</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="ch-poissonreg.html"><a href="ch-poissonreg.html#linear-least-squares-vs.-poisson-regression"><i class="fa fa-check"></i><b>4.5</b> Linear Least Squares  vs. Poisson Regression </a></li>
<li class="chapter" data-level="4.6" data-path="ch-poissonreg.html"><a href="ch-poissonreg.html#case-study-campus-crime"><i class="fa fa-check"></i><b>4.6</b> Case Study: Campus Crime</a><ul>
<li class="chapter" data-level="4.6.1" data-path="ch-poissonreg.html"><a href="ch-poissonreg.html#data-organization-1"><i class="fa fa-check"></i><b>4.6.1</b> Data Organization</a></li>
<li class="chapter" data-level="4.6.2" data-path="ch-poissonreg.html"><a href="ch-poissonreg.html#exploratory-data-analysis"><i class="fa fa-check"></i><b>4.6.2</b> Exploratory Data Analysis</a></li>
<li class="chapter" data-level="4.6.3" data-path="ch-poissonreg.html"><a href="ch-poissonreg.html#accounting-for-enrollment"><i class="fa fa-check"></i><b>4.6.3</b> Accounting for Enrollment</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="ch-poissonreg.html"><a href="ch-poissonreg.html#modeling-assumptions"><i class="fa fa-check"></i><b>4.7</b> Modeling Assumptions</a></li>
<li class="chapter" data-level="4.8" data-path="ch-poissonreg.html"><a href="ch-poissonreg.html#initial-models"><i class="fa fa-check"></i><b>4.8</b> Initial Models</a><ul>
<li class="chapter" data-level="4.8.1" data-path="ch-poissonreg.html"><a href="ch-poissonreg.html#tukeys-honestly-significant-differences"><i class="fa fa-check"></i><b>4.8.1</b> Tukey’s Honestly Significant Differences</a></li>
</ul></li>
<li class="chapter" data-level="4.9" data-path="ch-poissonreg.html"><a href="ch-poissonreg.html#sec-overdispPois"><i class="fa fa-check"></i><b>4.9</b> Overdispersion</a><ul>
<li class="chapter" data-level="4.9.1" data-path="ch-poissonreg.html"><a href="ch-poissonreg.html#dispersion-parameter-adjustment"><i class="fa fa-check"></i><b>4.9.1</b> Dispersion Parameter Adjustment</a></li>
<li class="chapter" data-level="4.9.2" data-path="ch-poissonreg.html"><a href="ch-poissonreg.html#no-dispersion-vs.-overdispersion"><i class="fa fa-check"></i><b>4.9.2</b> No Dispersion vs. Overdispersion</a></li>
<li class="chapter" data-level="4.9.3" data-path="ch-poissonreg.html"><a href="ch-poissonreg.html#negative-binomial-modeling"><i class="fa fa-check"></i><b>4.9.3</b> Negative Binomial Modeling</a></li>
</ul></li>
<li class="chapter" data-level="4.10" data-path="ch-poissonreg.html"><a href="ch-poissonreg.html#cs:drinking"><i class="fa fa-check"></i><b>4.10</b> Case Study: Weekend Drinking</a><ul>
<li class="chapter" data-level="4.10.1" data-path="ch-poissonreg.html"><a href="ch-poissonreg.html#research-question"><i class="fa fa-check"></i><b>4.10.1</b> Research Question</a></li>
<li class="chapter" data-level="4.10.2" data-path="ch-poissonreg.html"><a href="ch-poissonreg.html#data-organization-2"><i class="fa fa-check"></i><b>4.10.2</b> Data Organization</a></li>
<li class="chapter" data-level="4.10.3" data-path="ch-poissonreg.html"><a href="ch-poissonreg.html#exploratory-data-analysis-1"><i class="fa fa-check"></i><b>4.10.3</b> Exploratory Data Analysis</a></li>
<li class="chapter" data-level="4.10.4" data-path="ch-poissonreg.html"><a href="ch-poissonreg.html#modeling"><i class="fa fa-check"></i><b>4.10.4</b> Modeling</a></li>
<li class="chapter" data-level="4.10.5" data-path="ch-poissonreg.html"><a href="ch-poissonreg.html#fitting-a-zip-model"><i class="fa fa-check"></i><b>4.10.5</b> Fitting a ZIP Model</a></li>
<li class="chapter" data-level="4.10.6" data-path="ch-poissonreg.html"><a href="ch-poissonreg.html#the-vuong-test-optional"><i class="fa fa-check"></i><b>4.10.6</b> The Vuong Test (optional)</a></li>
<li class="chapter" data-level="4.10.7" data-path="ch-poissonreg.html"><a href="ch-poissonreg.html#residual-plot"><i class="fa fa-check"></i><b>4.10.7</b> Residual Plot</a></li>
<li class="chapter" data-level="4.10.8" data-path="ch-poissonreg.html"><a href="ch-poissonreg.html#limitations"><i class="fa fa-check"></i><b>4.10.8</b> Limitations</a></li>
</ul></li>
<li class="chapter" data-level="4.11" data-path="ch-poissonreg.html"><a href="ch-poissonreg.html#exercises-3"><i class="fa fa-check"></i><b>4.11</b> Exercises</a><ul>
<li class="chapter" data-level="4.11.1" data-path="ch-poissonreg.html"><a href="ch-poissonreg.html#exer:concept"><i class="fa fa-check"></i><b>4.11.1</b> Conceptual Exercises</a></li>
<li class="chapter" data-level="4.11.2" data-path="ch-poissonreg.html"><a href="ch-poissonreg.html#guided-exercises-3"><i class="fa fa-check"></i><b>4.11.2</b> Guided Exercises</a></li>
<li class="chapter" data-level="4.11.3" data-path="ch-poissonreg.html"><a href="ch-poissonreg.html#open-ended-exercises-2"><i class="fa fa-check"></i><b>4.11.3</b> Open-Ended Exercises</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="ch-glms.html"><a href="ch-glms.html"><i class="fa fa-check"></i><b>5</b> Generalized Linear Models: A Unifying Theory</a><ul>
<li class="chapter" data-level="5.1" data-path="ch-glms.html"><a href="ch-glms.html#learning-objectives-4"><i class="fa fa-check"></i><b>5.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="5.2" data-path="ch-glms.html"><a href="ch-glms.html#one-parameter-exponential-families"><i class="fa fa-check"></i><b>5.2</b> One-Parameter Exponential Families</a><ul>
<li class="chapter" data-level="5.2.1" data-path="ch-glms.html"><a href="ch-glms.html#one-parameter-exponential-family-poisson"><i class="fa fa-check"></i><b>5.2.1</b> One-Parameter Exponential Family: Poisson</a></li>
<li class="chapter" data-level="5.2.2" data-path="ch-glms.html"><a href="ch-glms.html#one-parameter-exponential-family-normal"><i class="fa fa-check"></i><b>5.2.2</b> One-Parameter Exponential Family: Normal</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="ch-glms.html"><a href="ch-glms.html#generalized-linear-modeling"><i class="fa fa-check"></i><b>5.3</b> Generalized Linear Modeling</a></li>
<li class="chapter" data-level="5.4" data-path="ch-glms.html"><a href="ch-glms.html#exercises-4"><i class="fa fa-check"></i><b>5.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="ch-logreg.html"><a href="ch-logreg.html"><i class="fa fa-check"></i><b>6</b> Logistic Regression</a><ul>
<li class="chapter" data-level="6.1" data-path="ch-logreg.html"><a href="ch-logreg.html#learning-objectives-5"><i class="fa fa-check"></i><b>6.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="6.2" data-path="ch-logreg.html"><a href="ch-logreg.html#introduction-to-logistic-regression"><i class="fa fa-check"></i><b>6.2</b> Introduction to Logistic Regression</a><ul>
<li class="chapter" data-level="6.2.1" data-path="ch-logreg.html"><a href="ch-logreg.html#logistic-regression-assumptions"><i class="fa fa-check"></i><b>6.2.1</b> Logistic Regression Assumptions</a></li>
<li class="chapter" data-level="6.2.2" data-path="ch-logreg.html"><a href="ch-logreg.html#a-graphical-look-at-logistic-regression"><i class="fa fa-check"></i><b>6.2.2</b> A Graphical Look at Logistic Regression</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="ch-logreg.html"><a href="ch-logreg.html#case-studies-overview-1"><i class="fa fa-check"></i><b>6.3</b> Case Studies Overview</a></li>
<li class="chapter" data-level="6.4" data-path="ch-logreg.html"><a href="ch-logreg.html#case-study-soccer-goalkeepers"><i class="fa fa-check"></i><b>6.4</b> Case Study: Soccer Goalkeepers</a><ul>
<li class="chapter" data-level="6.4.1" data-path="ch-logreg.html"><a href="ch-logreg.html#modeling-odds"><i class="fa fa-check"></i><b>6.4.1</b> Modeling Odds</a></li>
<li class="chapter" data-level="6.4.2" data-path="ch-logreg.html"><a href="ch-logreg.html#logistic-regression-models-for-binomial-responses"><i class="fa fa-check"></i><b>6.4.2</b> Logistic Regression Models for Binomial Responses</a></li>
<li class="chapter" data-level="6.4.3" data-path="ch-logreg.html"><a href="ch-logreg.html#theoretical-rationale-optional"><i class="fa fa-check"></i><b>6.4.3</b> Theoretical Rationale (optional)</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="ch-logreg.html"><a href="ch-logreg.html#case-study-reconstructing-alabama"><i class="fa fa-check"></i><b>6.5</b> Case Study: Reconstructing Alabama</a><ul>
<li class="chapter" data-level="6.5.1" data-path="ch-logreg.html"><a href="ch-logreg.html#data-organization-3"><i class="fa fa-check"></i><b>6.5.1</b> Data Organization</a></li>
<li class="chapter" data-level="6.5.2" data-path="ch-logreg.html"><a href="ch-logreg.html#exploratory-analyses"><i class="fa fa-check"></i><b>6.5.2</b> Exploratory Analyses</a></li>
<li class="chapter" data-level="6.5.3" data-path="ch-logreg.html"><a href="ch-logreg.html#initial-models-1"><i class="fa fa-check"></i><b>6.5.3</b> Initial Models</a></li>
<li class="chapter" data-level="6.5.4" data-path="ch-logreg.html"><a href="ch-logreg.html#sec-logisticInf"><i class="fa fa-check"></i><b>6.5.4</b> Tests for Significance of Model Coefficients</a></li>
<li class="chapter" data-level="6.5.5" data-path="ch-logreg.html"><a href="ch-logreg.html#confidence-intervals-for-model-coefficients"><i class="fa fa-check"></i><b>6.5.5</b> Confidence Intervals for Model Coefficients</a></li>
<li class="chapter" data-level="6.5.6" data-path="ch-logreg.html"><a href="ch-logreg.html#testing-for-goodness-of-fit"><i class="fa fa-check"></i><b>6.5.6</b> Testing for Goodness-of-Fit</a></li>
<li class="chapter" data-level="6.5.7" data-path="ch-logreg.html"><a href="ch-logreg.html#residuals-for-binomial-regression"><i class="fa fa-check"></i><b>6.5.7</b> Residuals for Binomial Regression</a></li>
<li class="chapter" data-level="6.5.8" data-path="ch-logreg.html"><a href="ch-logreg.html#sec-logOverdispersion"><i class="fa fa-check"></i><b>6.5.8</b> Overdispersion</a></li>
<li class="chapter" data-level="6.5.9" data-path="ch-logreg.html"><a href="ch-logreg.html#summary-1"><i class="fa fa-check"></i><b>6.5.9</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="ch-logreg.html"><a href="ch-logreg.html#linear-least-squares-vs.-binomial-regression"><i class="fa fa-check"></i><b>6.6</b> Linear Least Squares  vs. Binomial Regression </a></li>
<li class="chapter" data-level="6.7" data-path="ch-logreg.html"><a href="ch-logreg.html#case-study-trying-to-lose-weight"><i class="fa fa-check"></i><b>6.7</b> Case Study: Trying to Lose Weight</a><ul>
<li class="chapter" data-level="6.7.1" data-path="ch-logreg.html"><a href="ch-logreg.html#data-organization-4"><i class="fa fa-check"></i><b>6.7.1</b> Data Organization</a></li>
<li class="chapter" data-level="6.7.2" data-path="ch-logreg.html"><a href="ch-logreg.html#exploratory-data-analysis-2"><i class="fa fa-check"></i><b>6.7.2</b> Exploratory Data Analysis</a></li>
<li class="chapter" data-level="6.7.3" data-path="ch-logreg.html"><a href="ch-logreg.html#initial-models-2"><i class="fa fa-check"></i><b>6.7.3</b> Initial Models</a></li>
<li class="chapter" data-level="6.7.4" data-path="ch-logreg.html"><a href="ch-logreg.html#drop-in-deviance-tests"><i class="fa fa-check"></i><b>6.7.4</b> Drop-in-Deviance Tests</a></li>
<li class="chapter" data-level="6.7.5" data-path="ch-logreg.html"><a href="ch-logreg.html#model-discussion-and-summary"><i class="fa fa-check"></i><b>6.7.5</b> Model Discussion and Summary</a></li>
</ul></li>
<li class="chapter" data-level="6.8" data-path="ch-logreg.html"><a href="ch-logreg.html#exercises-5"><i class="fa fa-check"></i><b>6.8</b> Exercises</a><ul>
<li class="chapter" data-level="6.8.1" data-path="ch-logreg.html"><a href="ch-logreg.html#conceptual-exercises-3"><i class="fa fa-check"></i><b>6.8.1</b> Conceptual Exercises</a></li>
<li class="chapter" data-level="6.8.2" data-path="ch-logreg.html"><a href="ch-logreg.html#guided-exercises-4"><i class="fa fa-check"></i><b>6.8.2</b> Guided Exercises</a></li>
<li class="chapter" data-level="6.8.3" data-path="ch-logreg.html"><a href="ch-logreg.html#open-ended-exercises-3"><i class="fa fa-check"></i><b>6.8.3</b> Open-Ended Exercises</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="ch-corrdata.html"><a href="ch-corrdata.html"><i class="fa fa-check"></i><b>7</b> Correlated Data</a><ul>
<li class="chapter" data-level="7.1" data-path="ch-corrdata.html"><a href="ch-corrdata.html#learning-objectives-6"><i class="fa fa-check"></i><b>7.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="7.2" data-path="ch-corrdata.html"><a href="ch-corrdata.html#introduction-1"><i class="fa fa-check"></i><b>7.2</b> Introduction</a></li>
<li class="chapter" data-level="7.3" data-path="ch-corrdata.html"><a href="ch-corrdata.html#recognizing-correlation"><i class="fa fa-check"></i><b>7.3</b> Recognizing Correlation</a></li>
<li class="chapter" data-level="7.4" data-path="ch-corrdata.html"><a href="ch-corrdata.html#case-study-dams-and-pups"><i class="fa fa-check"></i><b>7.4</b> Case Study: Dams and Pups</a></li>
<li class="chapter" data-level="7.5" data-path="ch-corrdata.html"><a href="ch-corrdata.html#sources-of-variability"><i class="fa fa-check"></i><b>7.5</b> Sources of Variability</a></li>
<li class="chapter" data-level="7.6" data-path="ch-corrdata.html"><a href="ch-corrdata.html#scenario-1-no-covariates"><i class="fa fa-check"></i><b>7.6</b> Scenario 1: No Covariates</a></li>
<li class="chapter" data-level="7.7" data-path="ch-corrdata.html"><a href="ch-corrdata.html#scenario-2-dose-effect"><i class="fa fa-check"></i><b>7.7</b> Scenario 2: Dose Effect</a></li>
<li class="chapter" data-level="7.8" data-path="ch-corrdata.html"><a href="ch-corrdata.html#case-study-tree-growth"><i class="fa fa-check"></i><b>7.8</b> Case Study: Tree Growth</a><ul>
<li class="chapter" data-level="7.8.1" data-path="ch-corrdata.html"><a href="ch-corrdata.html#format-of-the-data-set"><i class="fa fa-check"></i><b>7.8.1</b> Format of the Data Set</a></li>
<li class="chapter" data-level="7.8.2" data-path="ch-corrdata.html"><a href="ch-corrdata.html#sources-of-variability-1"><i class="fa fa-check"></i><b>7.8.2</b> Sources of Variability</a></li>
<li class="chapter" data-level="7.8.3" data-path="ch-corrdata.html"><a href="ch-corrdata.html#analysis-preview-accounting-for-correlation"><i class="fa fa-check"></i><b>7.8.3</b> Analysis Preview: Accounting for Correlation</a></li>
</ul></li>
<li class="chapter" data-level="7.9" data-path="ch-corrdata.html"><a href="ch-corrdata.html#summary-2"><i class="fa fa-check"></i><b>7.9</b> Summary</a></li>
<li class="chapter" data-level="7.10" data-path="ch-corrdata.html"><a href="ch-corrdata.html#exercises-6"><i class="fa fa-check"></i><b>7.10</b> Exercises</a><ul>
<li class="chapter" data-level="7.10.1" data-path="ch-corrdata.html"><a href="ch-corrdata.html#conceptual-exercises-4"><i class="fa fa-check"></i><b>7.10.1</b> Conceptual Exercises</a></li>
<li class="chapter" data-level="7.10.2" data-path="ch-corrdata.html"><a href="ch-corrdata.html#guided-exercises-5"><i class="fa fa-check"></i><b>7.10.2</b> Guided Exercises</a></li>
<li class="chapter" data-level="7.10.3" data-path="ch-corrdata.html"><a href="ch-corrdata.html#note-on-correlated-binary-outcomes"><i class="fa fa-check"></i><b>7.10.3</b> Note on Correlated Binary Outcomes</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="ch-multilevelintro.html"><a href="ch-multilevelintro.html"><i class="fa fa-check"></i><b>8</b> Introduction to Multilevel Models</a><ul>
<li class="chapter" data-level="8.1" data-path="ch-multilevelintro.html"><a href="ch-multilevelintro.html#learning-objectives-7"><i class="fa fa-check"></i><b>8.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="8.2" data-path="ch-multilevelintro.html"><a href="ch-multilevelintro.html#cs:music"><i class="fa fa-check"></i><b>8.2</b> Case Study: Music Performance Anxiety</a></li>
<li class="chapter" data-level="8.3" data-path="ch-multilevelintro.html"><a href="ch-multilevelintro.html#explore"><i class="fa fa-check"></i><b>8.3</b> Initial Exploratory Analyses</a><ul>
<li class="chapter" data-level="8.3.1" data-path="ch-multilevelintro.html"><a href="ch-multilevelintro.html#organizedata1"><i class="fa fa-check"></i><b>8.3.1</b> Data Organization</a></li>
<li class="chapter" data-level="8.3.2" data-path="ch-multilevelintro.html"><a href="ch-multilevelintro.html#explore1"><i class="fa fa-check"></i><b>8.3.2</b> Exploratory Analyses: Univariate Summaries</a></li>
<li class="chapter" data-level="8.3.3" data-path="ch-multilevelintro.html"><a href="ch-multilevelintro.html#explore2"><i class="fa fa-check"></i><b>8.3.3</b> Exploratory Analyses: Bivariate Summaries</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="ch-multilevelintro.html"><a href="ch-multilevelintro.html#twolevelmodeling"><i class="fa fa-check"></i><b>8.4</b> Two-Level Modeling: Preliminary Considerations</a><ul>
<li class="chapter" data-level="8.4.1" data-path="ch-multilevelintro.html"><a href="ch-multilevelintro.html#multregr"><i class="fa fa-check"></i><b>8.4.1</b> Ignoring the Two-Level Structure (not recommended)</a></li>
<li class="chapter" data-level="8.4.2" data-path="ch-multilevelintro.html"><a href="ch-multilevelintro.html#twostage"><i class="fa fa-check"></i><b>8.4.2</b> A Two-Stage Modeling Approach (better but imperfect)</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="ch-multilevelintro.html"><a href="ch-multilevelintro.html#twolevelmodelingunified"><i class="fa fa-check"></i><b>8.5</b> Two-Level Modeling: A Unified Approach</a><ul>
<li class="chapter" data-level="8.5.1" data-path="ch-multilevelintro.html"><a href="ch-multilevelintro.html#ourframework"><i class="fa fa-check"></i><b>8.5.1</b> Our Framework</a></li>
<li class="chapter" data-level="8.5.2" data-path="ch-multilevelintro.html"><a href="ch-multilevelintro.html#random-vs.-fixed-effects"><i class="fa fa-check"></i><b>8.5.2</b> Random vs. Fixed Effects</a></li>
<li class="chapter" data-level="8.5.3" data-path="ch-multilevelintro.html"><a href="ch-multilevelintro.html#MVN"><i class="fa fa-check"></i><b>8.5.3</b> Distribution of Errors: Multivariate Normal</a></li>
<li class="chapter" data-level="8.5.4" data-path="ch-multilevelintro.html"><a href="ch-multilevelintro.html#multileveltechnical"><i class="fa fa-check"></i><b>8.5.4</b> Technical Issues when Testing Parameters (optional)</a></li>
<li class="chapter" data-level="8.5.5" data-path="ch-multilevelintro.html"><a href="ch-multilevelintro.html#initialmodel"><i class="fa fa-check"></i><b>8.5.5</b> An Initial Model with Parameter Interpretations</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="ch-multilevelintro.html"><a href="ch-multilevelintro.html#sec:buildmodel"><i class="fa fa-check"></i><b>8.6</b> Building a Multilevel Model</a><ul>
<li class="chapter" data-level="8.6.1" data-path="ch-multilevelintro.html"><a href="ch-multilevelintro.html#buildstrategy"><i class="fa fa-check"></i><b>8.6.1</b> Model Building Strategy</a></li>
<li class="chapter" data-level="8.6.2" data-path="ch-multilevelintro.html"><a href="ch-multilevelintro.html#modela8"><i class="fa fa-check"></i><b>8.6.2</b> An Initial Model: Random Intercepts</a></li>
</ul></li>
<li class="chapter" data-level="8.7" data-path="ch-multilevelintro.html"><a href="ch-multilevelintro.html#modelb"><i class="fa fa-check"></i><b>8.7</b> Binary Covariates at Level One and Level Two</a><ul>
<li class="chapter" data-level="8.7.1" data-path="ch-multilevelintro.html"><a href="ch-multilevelintro.html#randomslopeandint"><i class="fa fa-check"></i><b>8.7.1</b> Random Slopes and Intercepts Model</a></li>
<li class="chapter" data-level="8.7.2" data-path="ch-multilevelintro.html"><a href="ch-multilevelintro.html#pseudoR2"><i class="fa fa-check"></i><b>8.7.2</b> Pseudo R-squared Values</a></li>
<li class="chapter" data-level="8.7.3" data-path="ch-multilevelintro.html"><a href="ch-multilevelintro.html#modelc"><i class="fa fa-check"></i><b>8.7.3</b> Adding a Covariate at Level Two</a></li>
</ul></li>
<li class="chapter" data-level="8.8" data-path="ch-multilevelintro.html"><a href="ch-multilevelintro.html#sec:modeld"><i class="fa fa-check"></i><b>8.8</b> Adding Further Covariates</a><ul>
<li class="chapter" data-level="8.8.1" data-path="ch-multilevelintro.html"><a href="ch-multilevelintro.html#interp:modeld"><i class="fa fa-check"></i><b>8.8.1</b> Interpretation of Parameter Estimates</a></li>
<li class="chapter" data-level="8.8.2" data-path="ch-multilevelintro.html"><a href="ch-multilevelintro.html#compare:modeld"><i class="fa fa-check"></i><b>8.8.2</b> Model Comparisons</a></li>
</ul></li>
<li class="chapter" data-level="8.9" data-path="ch-multilevelintro.html"><a href="ch-multilevelintro.html#sec:modele"><i class="fa fa-check"></i><b>8.9</b> Centering Covariates</a></li>
<li class="chapter" data-level="8.10" data-path="ch-multilevelintro.html"><a href="ch-multilevelintro.html#modelf"><i class="fa fa-check"></i><b>8.10</b> A Final Model for Music Performance Anxiety</a></li>
<li class="chapter" data-level="8.11" data-path="ch-multilevelintro.html"><a href="ch-multilevelintro.html#multinecessary"><i class="fa fa-check"></i><b>8.11</b> Modeling Multilevel Structure: Is It Necessary?</a></li>
<li class="chapter" data-level="8.12" data-path="ch-multilevelintro.html"><a href="ch-multilevelintro.html#notesr8"><i class="fa fa-check"></i><b>8.12</b> Notes on Using R (optional)</a></li>
<li class="chapter" data-level="8.13" data-path="ch-multilevelintro.html"><a href="ch-multilevelintro.html#exercises-7"><i class="fa fa-check"></i><b>8.13</b> Exercises</a><ul>
<li class="chapter" data-level="8.13.1" data-path="ch-multilevelintro.html"><a href="ch-multilevelintro.html#conceptual-exercises-5"><i class="fa fa-check"></i><b>8.13.1</b> Conceptual Exercises</a></li>
<li class="chapter" data-level="8.13.2" data-path="ch-multilevelintro.html"><a href="ch-multilevelintro.html#guided-exercises-6"><i class="fa fa-check"></i><b>8.13.2</b> Guided Exercises</a></li>
<li class="chapter" data-level="8.13.3" data-path="ch-multilevelintro.html"><a href="ch-multilevelintro.html#open-ended-exercises-4"><i class="fa fa-check"></i><b>8.13.3</b> Open-Ended Exercises</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="ch-lon.html"><a href="ch-lon.html"><i class="fa fa-check"></i><b>9</b> Two-Level Longitudinal Data</a><ul>
<li class="chapter" data-level="9.1" data-path="ch-lon.html"><a href="ch-lon.html#learning-objectives-8"><i class="fa fa-check"></i><b>9.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="9.2" data-path="ch-lon.html"><a href="ch-lon.html#cs:charter"><i class="fa fa-check"></i><b>9.2</b> Case Study: Charter Schools</a></li>
<li class="chapter" data-level="9.3" data-path="ch-lon.html"><a href="ch-lon.html#exploratoryanalysis"><i class="fa fa-check"></i><b>9.3</b> Initial Exploratory Analyses</a><ul>
<li class="chapter" data-level="9.3.1" data-path="ch-lon.html"><a href="ch-lon.html#data"><i class="fa fa-check"></i><b>9.3.1</b> Data Organization</a></li>
<li class="chapter" data-level="9.3.2" data-path="ch-lon.html"><a href="ch-lon.html#missing"><i class="fa fa-check"></i><b>9.3.2</b> Missing Data</a></li>
<li class="chapter" data-level="9.3.3" data-path="ch-lon.html"><a href="ch-lon.html#generalanalyses"><i class="fa fa-check"></i><b>9.3.3</b> Exploratory Analyses for General Multilevel Models</a></li>
<li class="chapter" data-level="9.3.4" data-path="ch-lon.html"><a href="ch-lon.html#longitudinalanalyses"><i class="fa fa-check"></i><b>9.3.4</b> Exploratory Analyses for Longitudinal Data</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="ch-lon.html"><a href="ch-lon.html#twostage9"><i class="fa fa-check"></i><b>9.4</b> Preliminary Two-Stage Modeling</a><ul>
<li class="chapter" data-level="9.4.1" data-path="ch-lon.html"><a href="ch-lon.html#lineartwostage"><i class="fa fa-check"></i><b>9.4.1</b> Linear Trends Within Schools</a></li>
<li class="chapter" data-level="9.4.2" data-path="ch-lon.html"><a href="ch-lon.html#lineartwostageL2effects"><i class="fa fa-check"></i><b>9.4.2</b> Effects of Level Two Covariates on Linear Time Trends</a></li>
<li class="chapter" data-level="9.4.3" data-path="ch-lon.html"><a href="ch-lon.html#lineartwostageerror2"><i class="fa fa-check"></i><b>9.4.3</b> Error Structure Within Schools</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="ch-lon.html"><a href="ch-lon.html#lineartwostageerror"><i class="fa fa-check"></i><b>9.5</b> Initial Models</a><ul>
<li class="chapter" data-level="9.5.1" data-path="ch-lon.html"><a href="ch-lon.html#modela"><i class="fa fa-check"></i><b>9.5.1</b> Unconditional Means Model</a></li>
<li class="chapter" data-level="9.5.2" data-path="ch-lon.html"><a href="ch-lon.html#modelb9"><i class="fa fa-check"></i><b>9.5.2</b> Unconditional Growth Model</a></li>
<li class="chapter" data-level="9.5.3" data-path="ch-lon.html"><a href="ch-lon.html#othertimetrends"><i class="fa fa-check"></i><b>9.5.3</b> Modeling Other Trends over Time</a></li>
</ul></li>
<li class="chapter" data-level="9.6" data-path="ch-lon.html"><a href="ch-lon.html#finalmodel"><i class="fa fa-check"></i><b>9.6</b> Building to a Final Model</a><ul>
<li class="chapter" data-level="9.6.1" data-path="ch-lon.html"><a href="ch-lon.html#sec:modelc9"><i class="fa fa-check"></i><b>9.6.1</b> Uncontrolled Effects of School Type</a></li>
<li class="chapter" data-level="9.6.2" data-path="ch-lon.html"><a href="ch-lon.html#modeld"><i class="fa fa-check"></i><b>9.6.2</b> Add Percent Free and Reduced Lunch as a Covariate</a></li>
<li class="chapter" data-level="9.6.3" data-path="ch-lon.html"><a href="ch-lon.html#modelf9"><i class="fa fa-check"></i><b>9.6.3</b> A Final Model with Three Level Two Covariates</a></li>
<li class="chapter" data-level="9.6.4" data-path="ch-lon.html"><a href="ch-lon.html#longitudinal-paraboot"><i class="fa fa-check"></i><b>9.6.4</b> Parametric Bootstrap Testing</a></li>
</ul></li>
<li class="chapter" data-level="9.7" data-path="ch-lon.html"><a href="ch-lon.html#errorcovariance"><i class="fa fa-check"></i><b>9.7</b> Covariance Structure among Observations</a><ul>
<li class="chapter" data-level="9.7.1" data-path="ch-lon.html"><a href="ch-lon.html#standarderror"><i class="fa fa-check"></i><b>9.7.1</b> Standard Covariance Structure</a></li>
<li class="chapter" data-level="9.7.2" data-path="ch-lon.html"><a href="ch-lon.html#alternateerror"><i class="fa fa-check"></i><b>9.7.2</b> Alternative Covariance Structures</a></li>
<li class="chapter" data-level="9.7.3" data-path="ch-lon.html"><a href="ch-lon.html#non-longitudinal-multilevel-models"><i class="fa fa-check"></i><b>9.7.3</b> Non-longitudinal Multilevel Models</a></li>
<li class="chapter" data-level="9.7.4" data-path="ch-lon.html"><a href="ch-lon.html#final-thoughts-regarding-covariance-structures"><i class="fa fa-check"></i><b>9.7.4</b> Final Thoughts Regarding Covariance Structures</a></li>
<li class="chapter" data-level="9.7.5" data-path="ch-lon.html"><a href="ch-lon.html#optionalcov"><i class="fa fa-check"></i><b>9.7.5</b> Details of Covariance Structures (optional)</a></li>
</ul></li>
<li class="chapter" data-level="9.8" data-path="ch-lon.html"><a href="ch-lon.html#notesr9"><i class="fa fa-check"></i><b>9.8</b> Notes on Using R (optional)</a></li>
<li class="chapter" data-level="9.9" data-path="ch-lon.html"><a href="ch-lon.html#exercises-8"><i class="fa fa-check"></i><b>9.9</b> Exercises</a><ul>
<li class="chapter" data-level="9.9.1" data-path="ch-lon.html"><a href="ch-lon.html#conceptual-exercises-6"><i class="fa fa-check"></i><b>9.9.1</b> Conceptual Exercises</a></li>
<li class="chapter" data-level="9.9.2" data-path="ch-lon.html"><a href="ch-lon.html#guided-exercises-7"><i class="fa fa-check"></i><b>9.9.2</b> Guided Exercises</a></li>
<li class="chapter" data-level="9.9.3" data-path="ch-lon.html"><a href="ch-lon.html#open-ended-exercises-5"><i class="fa fa-check"></i><b>9.9.3</b> Open-Ended Exercises</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="ch-3level.html"><a href="ch-3level.html"><i class="fa fa-check"></i><b>10</b> Multilevel Data With More Than Two Levels</a><ul>
<li class="chapter" data-level="10.1" data-path="ch-3level.html"><a href="ch-3level.html#learning-objectives-9"><i class="fa fa-check"></i><b>10.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="10.2" data-path="ch-3level.html"><a href="ch-3level.html#cs:seeds"><i class="fa fa-check"></i><b>10.2</b> Case Studies: Seed Germination</a></li>
<li class="chapter" data-level="10.3" data-path="ch-3level.html"><a href="ch-3level.html#explore3"><i class="fa fa-check"></i><b>10.3</b> Initial Exploratory Analyses</a><ul>
<li class="chapter" data-level="10.3.1" data-path="ch-3level.html"><a href="ch-3level.html#organizedata3"><i class="fa fa-check"></i><b>10.3.1</b> Data Organization</a></li>
<li class="chapter" data-level="10.3.2" data-path="ch-3level.html"><a href="ch-3level.html#explore3v2"><i class="fa fa-check"></i><b>10.3.2</b> Exploratory Analyses</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="ch-3level.html"><a href="ch-3level.html#initialmodels-3level"><i class="fa fa-check"></i><b>10.4</b> Initial Models</a><ul>
<li class="chapter" data-level="10.4.1" data-path="ch-3level.html"><a href="ch-3level.html#unconditional-means"><i class="fa fa-check"></i><b>10.4.1</b> Unconditional Means</a></li>
<li class="chapter" data-level="10.4.2" data-path="ch-3level.html"><a href="ch-3level.html#unconditional-growth"><i class="fa fa-check"></i><b>10.4.2</b> Unconditional Growth</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="ch-3level.html"><a href="ch-3level.html#sec:boundary"><i class="fa fa-check"></i><b>10.5</b> Encountering Boundary Constraints</a></li>
<li class="chapter" data-level="10.6" data-path="ch-3level.html"><a href="ch-3level.html#threelevel-paraboot"><i class="fa fa-check"></i><b>10.6</b> Parametric Bootstrap Testing</a></li>
<li class="chapter" data-level="10.7" data-path="ch-3level.html"><a href="ch-3level.html#sec:explodingvarcomps"><i class="fa fa-check"></i><b>10.7</b> Exploding Variance Components</a></li>
<li class="chapter" data-level="10.8" data-path="ch-3level.html"><a href="ch-3level.html#modelsDEF"><i class="fa fa-check"></i><b>10.8</b> Building to a Final Model</a></li>
<li class="chapter" data-level="10.9" data-path="ch-3level.html"><a href="ch-3level.html#error-3level"><i class="fa fa-check"></i><b>10.9</b> Covariance Structure (optional)</a><ul>
<li class="chapter" data-level="10.9.1" data-path="ch-3level.html"><a href="ch-3level.html#optionalerror"><i class="fa fa-check"></i><b>10.9.1</b> Details of Covariance Structures</a></li>
</ul></li>
<li class="chapter" data-level="10.10" data-path="ch-3level.html"><a href="ch-3level.html#usingR3"><i class="fa fa-check"></i><b>10.10</b> Notes on Using R (optional)</a></li>
<li class="chapter" data-level="10.11" data-path="ch-3level.html"><a href="ch-3level.html#exercises-9"><i class="fa fa-check"></i><b>10.11</b> Exercises</a><ul>
<li class="chapter" data-level="10.11.1" data-path="ch-3level.html"><a href="ch-3level.html#conceptual-exercises-7"><i class="fa fa-check"></i><b>10.11.1</b> Conceptual Exercises</a></li>
<li class="chapter" data-level="10.11.2" data-path="ch-3level.html"><a href="ch-3level.html#guided-exercises-8"><i class="fa fa-check"></i><b>10.11.2</b> Guided Exercises</a></li>
<li class="chapter" data-level="10.11.3" data-path="ch-3level.html"><a href="ch-3level.html#open-ended-exercises-6"><i class="fa fa-check"></i><b>10.11.3</b> Open-Ended Exercises</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="ch-GLMM.html"><a href="ch-GLMM.html"><i class="fa fa-check"></i><b>11</b> Multilevel Generalized Linear Models</a><ul>
<li class="chapter" data-level="11.1" data-path="ch-GLMM.html"><a href="ch-GLMM.html#objectives"><i class="fa fa-check"></i><b>11.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="11.2" data-path="ch-GLMM.html"><a href="ch-GLMM.html#cs:refs"><i class="fa fa-check"></i><b>11.2</b> Case Study: College Basketball Referees</a></li>
<li class="chapter" data-level="11.3" data-path="ch-GLMM.html"><a href="ch-GLMM.html#explore-glmm"><i class="fa fa-check"></i><b>11.3</b> Initial Exploratory Analyses</a><ul>
<li class="chapter" data-level="11.3.1" data-path="ch-GLMM.html"><a href="ch-GLMM.html#data-organization-5"><i class="fa fa-check"></i><b>11.3.1</b> Data Organization</a></li>
<li class="chapter" data-level="11.3.2" data-path="ch-GLMM.html"><a href="ch-GLMM.html#glmm-eda"><i class="fa fa-check"></i><b>11.3.2</b> Exploratory Analyses</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="ch-GLMM.html"><a href="ch-GLMM.html#twolevelmodeling-glmm"><i class="fa fa-check"></i><b>11.4</b> Two-Level Modeling with a Generalized Response</a><ul>
<li class="chapter" data-level="11.4.1" data-path="ch-GLMM.html"><a href="ch-GLMM.html#multregr-glmm"><i class="fa fa-check"></i><b>11.4.1</b> A GLM Approach</a></li>
<li class="chapter" data-level="11.4.2" data-path="ch-GLMM.html"><a href="ch-GLMM.html#twostage-glmm"><i class="fa fa-check"></i><b>11.4.2</b> A Two-Stage Modeling Approach</a></li>
<li class="chapter" data-level="11.4.3" data-path="ch-GLMM.html"><a href="ch-GLMM.html#unified-glmm"><i class="fa fa-check"></i><b>11.4.3</b> A Unified Multilevel Approach</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="ch-GLMM.html"><a href="ch-GLMM.html#crossedre"><i class="fa fa-check"></i><b>11.5</b> Crossed Random Effects</a></li>
<li class="chapter" data-level="11.6" data-path="ch-GLMM.html"><a href="ch-GLMM.html#glmm-paraboot"><i class="fa fa-check"></i><b>11.6</b> Parametric Bootstrap for Model Comparisons</a></li>
<li class="chapter" data-level="11.7" data-path="ch-GLMM.html"><a href="ch-GLMM.html#sec:finalmodel-glmm"><i class="fa fa-check"></i><b>11.7</b> A Final Model for Examining Referee Bias</a></li>
<li class="chapter" data-level="11.8" data-path="ch-GLMM.html"><a href="ch-GLMM.html#estimatedRE"><i class="fa fa-check"></i><b>11.8</b> Estimated Random Effects</a></li>
<li class="chapter" data-level="11.9" data-path="ch-GLMM.html"><a href="ch-GLMM.html#usingR-glmm"><i class="fa fa-check"></i><b>11.9</b> Notes on Using R (optional)</a></li>
<li class="chapter" data-level="11.10" data-path="ch-GLMM.html"><a href="ch-GLMM.html#exercises-10"><i class="fa fa-check"></i><b>11.10</b> Exercises</a><ul>
<li class="chapter" data-level="11.10.1" data-path="ch-GLMM.html"><a href="ch-GLMM.html#conceptual-exercises-8"><i class="fa fa-check"></i><b>11.10.1</b> Conceptual Exercises</a></li>
<li class="chapter" data-level="11.10.2" data-path="ch-GLMM.html"><a href="ch-GLMM.html#open-ended-exercises-7"><i class="fa fa-check"></i><b>11.10.2</b> Open-Ended Exercises</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Beyond Multiple Linear Regression</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="ch-logreg" class="section level1">
<h1><span class="header-section-number">Chapter 6</span> Logistic Regression</h1>

<div id="learning-objectives-5" class="section level2">
<h2><span class="header-section-number">6.1</span> Learning Objectives</h2>
<ul>
<li>Identify a binomial random variable and assess the validity of the binomial assumptions.</li>
<li>Write a generalized linear model for binomial responses in two forms, one as a function of the logit and one as a function of <span class="math inline">\(p\)</span>.</li>
<li>Explain how fitting a logistic regression differs from fitting a linear least squares regression (LLSR) model.</li>
<li>Interpret estimated coefficients in logistic regression.</li>
<li>Differentiate between logistic regression models with binary and binomial responses.</li>
<li>Use the residual deviance to compare models, to test for lack-of-fit when appropriate, and to check for unusual observations or needed transformations.</li>
</ul>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="ch-logreg.html#cb116-1"></a><span class="co"># Packages required for Chapter 6</span></span>
<span id="cb116-2"><a href="ch-logreg.html#cb116-2"></a><span class="kw">library</span>(gridExtra)  </span>
<span id="cb116-3"><a href="ch-logreg.html#cb116-3"></a><span class="kw">library</span>(mnormt) </span>
<span id="cb116-4"><a href="ch-logreg.html#cb116-4"></a><span class="kw">library</span>(lme4) </span>
<span id="cb116-5"><a href="ch-logreg.html#cb116-5"></a><span class="kw">library</span>(knitr) </span>
<span id="cb116-6"><a href="ch-logreg.html#cb116-6"></a><span class="kw">library</span>(pander)</span>
<span id="cb116-7"><a href="ch-logreg.html#cb116-7"></a><span class="kw">library</span>(tidyverse)</span></code></pre></div>
</div>
<div id="introduction-to-logistic-regression" class="section level2">
<h2><span class="header-section-number">6.2</span> Introduction to Logistic Regression</h2>
<p>Logistic regression is characterized by research questions with binary (yes/no or success/failure) or binomial (number of yesses or successes in <span class="math inline">\(n\)</span> trials) responses:</p>
<ol style="list-style-type: lower-alpha">
<li>Are students with poor grades more likely to binge drink?</li>
<li>Is exposure to a particular chemical associated with a cancer diagnosis?</li>
<li>Are the number of votes for a congressional candidate associated with the amount of campaign contributions?</li>
</ol>
<p><strong>Binary Responses:</strong> Recall from Section <a href="ch-distthry.html#sec-binary">3.3.1</a> that binary responses take on only two values: success (Y=1) or failure (Y=0), Yes (Y=1) or No (Y=0), etc. Binary responses are ubiquitous; they are one of the most common types of data that statisticians encounter. We are often interested in modeling the probability of success <span class="math inline">\(p\)</span> based on a set of covariates, although sometimes we wish to use those covariates to classify a future observation as a success or a failure.</p>
<p>Examples (a) and (b) above would be considered to have binary responses (Does a student binge drink? Was a patient diagnosed with cancer?), assuming that we have a unique set of covariates for each individual student or patient.</p>
<p><strong>Binomial Responses:</strong> Also recall from Section <a href="ch-distthry.html#sec-binomial">3.3.2</a> that binomial responses are the number of successes in <span class="math inline">\(n\)</span> identical, independent trials with constant probability <span class="math inline">\(p\)</span> of success. A sequence of independent trials like this with the same probability of success is called a <strong>Bernoulli process</strong>.  As with binary responses, our objective in modeling binomial responses is to quantify how the probability of success, <span class="math inline">\(p\)</span>, is associated with relevant covariates.</p>
<p>Example (c) above would be considered to have a binomial response, assuming we have vote totals at the congressional district level rather than information on individual voters.</p>
<div id="logistic-regression-assumptions" class="section level3">
<h3><span class="header-section-number">6.2.1</span> Logistic Regression Assumptions</h3>
<p>Much like ordinary least squares (OLS), using <strong>logistic regression</strong>  to make inferences requires model assumptions.</p>
<ol style="list-style-type: decimal">
<li><strong>Binary Response</strong> The response variable is dichotomous (two possible responses) or the sum of dichotomous responses.</li>
<li><strong>Independence</strong> The observations must be independent of one another.</li>
<li><strong>Variance Structure</strong> By definition, the variance of a binomial random variable is <span class="math inline">\(np(1-p)\)</span>, so that variability is highest when <span class="math inline">\(p=.5\)</span>.</li>
<li><strong>Linearity</strong> The log of the odds ratio, log(<span class="math inline">\(\frac{p}{1-p}\)</span>), must be a linear function of <span class="math inline">\(x\)</span>. This will be explained further in the context of the first case study.</li>
</ol>
</div>
<div id="a-graphical-look-at-logistic-regression" class="section level3">
<h3><span class="header-section-number">6.2.2</span> A Graphical Look at Logistic Regression</h3>
<div class="figure" style="text-align: center"><span id="fig:OLSlogistic"></span>
<img src="bookdown-BeyondMLR_files/figure-html/OLSlogistic-1.png" alt="Linear vs. logistic regression models for binary response data." width="60%" />
<p class="caption">
Figure 6.1: Linear vs. logistic regression models for binary response data.
</p>
</div>
<p>Figure <a href="ch-logreg.html#fig:OLSlogistic">6.1</a> illustrates a data set with a binary (0 or 1) response (Y) and a single continuous predictor (X). The solid line is a linear regression fit with least squares to model the probability of a success (Y=1) for a given value of X. With a binary response, the line doesn’t fit the data well, and it produces predicted probabilities below 0 and above 1. On the other hand, the logistic regression fit (dashed curve) with its typical “S” shape follows the data closely and always produces predicted probabilities between 0 and 1. For these and several other reasons detailed in this chapter, we will focus on the following model for logistic regression with binary or binomial responses:</p>
<p><span class="math display">\[\begin{equation*}
log(\frac{p_i}{1-p_i})=\beta_0+\beta_1 x_i
\end{equation*}\]</span>
where the observed values <span class="math inline">\(Y_i \sim\)</span> binomial with <span class="math inline">\(p=p_i\)</span> for a given <span class="math inline">\(x_i\)</span> and <span class="math inline">\(n=1\)</span> for binary responses.</p>
</div>
</div>
<div id="case-studies-overview-1" class="section level2">
<h2><span class="header-section-number">6.3</span> Case Studies Overview</h2>
<p>We consider three case studies in this chapter. The first two involve binomial responses (Soccer Goalkeepers and Reconstructing Alabama), while the last case uses a binary response (Trying to Lose Weight). Even though binary responses are much more common, their models have a very similar form to binomial responses, so the first two case studies will illustrate important principles that also apply to the binary case. Here are the statistical concepts you will encounter for each case study.</p>
<p>The soccer goalkeeper data can be written in the form of a 2 <span class="math inline">\(\times\)</span> 2 table. This example is used to describe some of the underlying theory for logistic regression. We demonstrate how binomial probability mass functions (pmfs) can be written in one-parameter exponential family form, from which we can identify the canonical link as in Chapter <a href="ch-glms.html#ch-glms">5</a>. Using the canonical link, we write a Generalized Linear Model for binomial counts and determine corresponding MLEs for model coefficients. Interpretation of the estimated parameters involves a fundamental concept, the odds ratio.</p>
<p>The Reconstructing Alabama case study is another binomial example which introduces the notion of deviances, which are used to compare and assess models. Thus, we will investigate hypothesis tests and confidence intervals, including issues of interaction terms, overdispersion, and lack-of-fit. We will also check the assumptions of logistic regression using empirical logit plots and deviance residuals.</p>
<p>The last case study addresses why teens try to lose weight. Here the response is a binary variable which allows us to analyze individual level data. The analysis builds on concepts from the previous sections in the context of a random sample from CDC’s Youth Risk Behavior Survey (YRBS).</p>
</div>
<div id="case-study-soccer-goalkeepers" class="section level2">
<h2><span class="header-section-number">6.4</span> Case Study: Soccer Goalkeepers</h2>
<p>Does the probability of a save in a soccer match depend upon whether the goalkeeper’s team is behind or not? <span class="citation">Roskes et al. (<a href="#ref-Roskes2011" role="doc-biblioref">2011</a>)</span> looked at penalty kicks in the men’s World Cup soccer championships from 1982 to 2010, and they assembled data on 204 penalty kicks during shootouts. The data for this study is summarized in Table <a href="ch-logreg.html#tab:table1chp6">6.1</a>.</p>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:table1chp6">Table 6.1: </span>Soccer goalkeepers’ penalty kick saves when their team is and is not behind.
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Saves
</th>
<th style="text-align:right;">
Scores
</th>
<th style="text-align:right;">
Total
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Behind
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
22
</td>
<td style="text-align:right;">
24
</td>
</tr>
<tr>
<td style="text-align:left;">
Not Behind
</td>
<td style="text-align:right;">
39
</td>
<td style="text-align:right;">
141
</td>
<td style="text-align:right;">
180
</td>
</tr>
<tr>
<td style="text-align:left;">
Total
</td>
<td style="text-align:right;">
41
</td>
<td style="text-align:right;">
163
</td>
<td style="text-align:right;">
204
</td>
</tr>
</tbody>
<tfoot>
<tr>
<td style="padding: 0; border:0;" colspan="100%">
<sup></sup> (Source: Roskes et al. 2011.)
</td>
</tr>
</tfoot>
</table>
<div id="modeling-odds" class="section level3">
<h3><span class="header-section-number">6.4.1</span> Modeling Odds</h3>
<p>Odds are one way to quantify a goalkeeper’s performance. Here the odds that a goalkeeper makes a save when his team is behind is 2 to 22 or 0.09 to 1. Or equivalently, the odds that a goal is scored on a penalty kick is 22 to 2 or 11 to 1. An odds of 11 to 1 tells you that a shooter whose team is ahead will score 11 times for every 1 shot that the goalkeeper saves. When the goalkeeper’s team is not behind the odds a goal is scored is 141 to 39 or 3.61 to 1. We see that the odds of a goal scored on a penalty kick are better when the goalkeeper’s team is behind than when it is not behind (i.e., better odds of scoring for the shooter when the shooter’s team is ahead). We can compare these odds by calculating the <strong>odds ratio</strong>  (OR), 11/3.61 or 3.05, which tells us that the <em>odds</em> of a successful penalty kick are 3.05 times higher when the shooter’s team is leading.</p>
<p>In our example, it is also possible to estimate the probability of a goal, <span class="math inline">\(p\)</span>, for either circumstance. When the goalkeeper’s team is behind, the probability of a successful penalty kick is <span class="math inline">\(p\)</span> = 22/24 or 0.833. We can see that the ratio of the probability of a goal scored divided by the probability of no goal is <span class="math inline">\((22/24)/(2/24)=22/2\)</span> or 11, the odds we had calculated above. The same calculation can be made when the goalkeeper’s team is not behind. In general, we now have several ways of finding the odds of success under certain circumstances:</p>
<p><span class="math display">\[\textrm{Odds} = \frac{\# \textrm{successes}}{\# \textrm{failures}}=
\frac{\# \textrm{successes}/n}{\# \textrm{failures}/n}=
\frac{p}{1-p}.\]</span></p>
</div>
<div id="logistic-regression-models-for-binomial-responses" class="section level3">
<h3><span class="header-section-number">6.4.2</span> Logistic Regression Models for Binomial Responses</h3>
<p>We would like to model the odds of success; however, odds are strictly positive. Therefore, similar to modeling log(<span class="math inline">\(\lambda\)</span>) in Poisson regression, which allowed the response to take on values from <span class="math inline">\(-\infty\)</span> to <span class="math inline">\(\infty\)</span>, we will model the log(odds), the <strong>logit</strong>,  in logistic regression. Logits will be suitable for modeling with a linear function of the predictors:</p>
<p><span class="math display">\[\begin{equation*}
\log\left(\frac{p}{1 - p}\right)=\beta_0+\beta_1X 
 \end{equation*}\]</span>
Models of this form are referred to as <strong>binomial regression models</strong>,  or more generally as <strong>logistic regression models</strong>.  Here we provide intuition for using and interpreting logistic regression models, and then in the short optional section that follows, we present rationale for these models using GLM theory.</p>
<p>In our example we could define <span class="math inline">\(X=0\)</span> for not behind and <span class="math inline">\(X=1\)</span> for behind and fit the model:</p>
<p><span class="math display" id="eq:logitXform">\[\begin{equation}
\log\left(\frac{p_X}{1-p_X}\right)=\beta_0 +\beta_1X
\tag{6.1}
\end{equation}\]</span>
where <span class="math inline">\(p_X\)</span> is the probability of a successful penalty kick given <span class="math inline">\(X\)</span>.</p>
<p>So, based on this model, the log odds of a successful penalty kick when the goalkeeper’s team is not behind is:</p>
<p><span class="math display">\[
\log\left(\frac{p_0}{1-p_0}\right) =\beta_0 \nonumber,
\]</span>
and the log odds when the team is behind is:</p>
<p><span class="math display">\[
\log\left(\frac{p_1}{1-p_1}\right)=\beta_0+\beta_1. \nonumber
\]</span></p>
<p>We can see that <span class="math inline">\(\beta_1\)</span> is the difference between the log odds of a successful penalty kick between games when the goalkeeper’s team is behind and games when the team is not behind. Using rules of logs:</p>
<p><span class="math display">\[\begin{equation*}
\beta_1 = (\beta_0 + \beta_1) - \beta_0 = 
\log\left(\frac{p_1}{1-p_1}\right) - \log\left(\frac{p_0}{1-p_0}\right) =
\log\left(\frac{p_1/(1-p_1)}{p_0/{(1-p_0)}}\right).
\end{equation*}\]</span></p>
<p>Thus <span class="math inline">\(e^{\beta_1}\)</span> is the ratio of the odds of scoring when the goalkeeper’s team is not behind compared to scoring when the team is behind. In general, <em>exponentiated coefficients in logistic regression are odds ratios (OR)</em>. A general interpretation of an OR is the odds of success for group A compared to the odds of success for group B—how many times greater the odds of success are in group A compared to group B.</p>
<p>The logit model (Equation <a href="ch-logreg.html#eq:logitXform">(6.1)</a>) can also be re-written in a <strong>probability form</strong>:</p>
<p><span class="math display">\[\begin{equation*} 
p_X=\frac{e^{\beta_0+\beta_1X}}{1+e^{\beta_0+\beta_1X}}
\end{equation*}\]</span>
which can be re-written for games when the goalkeeper’s team is behind as:</p>
<p><span class="math display" id="eq:pBehindform">\[\begin{equation} 
p_1=\frac{e^{\beta_0+\beta_1}}{1+e^{\beta_0+\beta_1}}  
\tag{6.2}
\end{equation}\]</span>
and for games when the goalkeeper’s team is not behind as:</p>
<p><span class="math display" id="eq:pNotBehindform">\[\begin{equation} 
p_0=\frac{e^{\beta_0}}{1+e^{\beta_0}}
\tag{6.3}
\end{equation}\]</span></p>
<p>We use likelihood methods to estimate <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>. As we had done in Chapter <a href="ch-beyondmost.html#ch-beyondmost">2</a>, we can write the likelihood for this example in the following form:</p>
<p><span class="math display">\[\mathrm{Lik}(p_1, p_0) = {24 \choose 22}p_1^{22}(1-p_1)^{2}
{180 \choose 141}p_0^{141}(1-p_0)^{39}\]</span></p>
<p>Our interest centers on estimating <span class="math inline">\(\hat{\beta_0}\)</span> and <span class="math inline">\(\hat{\beta_1}\)</span>, not <span class="math inline">\(p_1\)</span> or <span class="math inline">\(p_0\)</span>. So we replace <span class="math inline">\(p_1\)</span> in the likelihood with an expression for <span class="math inline">\(p_1\)</span> in terms of <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> as in Equation <a href="ch-logreg.html#eq:pBehindform">(6.2)</a>. Similarly, <span class="math inline">\(p_0\)</span> in Equation <a href="ch-logreg.html#eq:pNotBehindform">(6.3)</a> involves only <span class="math inline">\(\beta_0\)</span>. After removing constants, the new likelihood looks like:</p>
<p><span class="math display">\[\begin{equation*}
\begin{gathered}
    \mathrm{Lik}(\beta_0,\beta_1) \propto \\
    \left( \frac{e^{\beta_0+\beta_1}}{1+e^{\beta_0+\beta_1}}\right)^{22}\left(1- \frac{e^{\beta_0+\beta_1}}{1+e^{\beta_0+\beta_1}}\right)^{2}
    \left(\frac{e^{\beta_0}}{1+e^{\beta_0}}\right)^{141}\left(1-\frac{e^{\beta_0}}{1+e^{\beta_0}}\right)^{39}
\end{gathered}
\end{equation*}\]</span></p>
<p>Now what? Fitting the model means finding estimates of <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>, but familiar methods from calculus for maximizing the likelihood don’t work here. Instead, we consider all possible combinations of <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>. That is, we will pick that pair of values for <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> that yield the largest likelihood for our data. Trial and error to find the best pair is tedious at best, but more efficient numerical methods are available. The MLEs for the coefficients in the soccer goalkeeper study are <span class="math inline">\(\hat{\beta_0}= 1.2852\)</span> and <span class="math inline">\(\hat{\beta_1}=1.1127\)</span>.</p>
<p>Exponentiating <span class="math inline">\(\hat{\beta_1}\)</span> provides an estimate of the odds ratio (the odds of scoring when the goalkeeper’s team is behind, compared to the odds of scoring when the team is not behind) of 3.04, which is consistent with our calculations using the 2 <span class="math inline">\(\times\)</span> 2 table. We estimate that the odds of scoring when the goalkeeper’s team is behind is over 3 times that of when the team is not behind or, in other words, the odds a shooter is successful in a penalty kick shootout are 3.04 times higher when his team is leading.
</p>
<p><strong>Time out for study discussion (optional).</strong></p>
<ul>
<li><p>Discuss the following quote from the study abstract: “Because penalty takers shot at the two sides of the goal equally often, the goalkeepers’ right-oriented bias was dysfunctional, allowing more goals to be scored.”</p></li>
<li><p>Construct an argument for why the greater success observed when the goalkeeper’s team was behind might be better explained from the shooter’s perspective.</p></li>
</ul>
<p>Before we go on, you may be curious as to why there is <em>no error term</em> in our model statements for logistic or Poisson regression. One way to look at it is to consider that all models describe how observed values are generated. With the logistic model we assume that the observations are generated as binomial random variables. Each observation or realization of <span class="math inline">\(Y\)</span> = number of successes in <span class="math inline">\(n\)</span> independent and identical trials with a probability of success on any one trial of <span class="math inline">\(p\)</span> is produced by <span class="math inline">\(Y \sim \textrm{Binomial}(n,p)\)</span>. So the randomness in this model is not introduced by an added error term, but rather by appealing to a binomial probability distribution, where variability depends only on <span class="math inline">\(n\)</span> and <span class="math inline">\(p\)</span> through <span class="math inline">\(\textrm{Var}(Y)=np(1-p)\)</span>, and where <span class="math inline">\(n\)</span> is usually considered fixed and <span class="math inline">\(p\)</span> the parameter of interest.</p>
</div>
<div id="theoretical-rationale-optional" class="section level3">
<h3><span class="header-section-number">6.4.3</span> Theoretical Rationale (optional)</h3>
<p>Recall from Chapter <a href="ch-glms.html#ch-glms">5</a> that generalized linear models (GLMs)  are a way in which to model a variety of different types of responses. In this chapter, we apply the general results of GLMs to the specific application of binomial responses. Let <span class="math inline">\(Y\)</span> = the number scored out of <span class="math inline">\(n\)</span> penalty kicks. The parameter, <span class="math inline">\(p\)</span>, is the probability of a score on a single penalty kick. Recall that the theory of GLMs is based on the unifying notion of the one-parameter exponential family form:</p>
<p><span class="math display">\[\begin{equation*}
f(y;\theta)=e^{[a(y)b(\theta)+c(\theta)+d(y)]}
\end{equation*}\]</span>
To see that we can apply the general approach of GLMs  to binomial responses, we first write an expression for the probability of a binomial response and then use a little algebra to rewrite it until we can demonstrate that it, too, can be written in one-parameter exponential family form with <span class="math inline">\(\theta = p\)</span>. This will provide a way in which to specify the canonical link and the form for the model. Additional theory allows us to deduce the mean, standard deviation, and more from this form.</p>
<p>If <span class="math inline">\(Y\)</span> follows a binomial distribution with <span class="math inline">\(n\)</span> trials and probability of success <span class="math inline">\(p\)</span>, we can write:</p>
<p><span class="math display">\[\begin{align*}
P(Y=y)&amp;= \binom{n}{y}p^y(1-p)^{(n-y)} \\
      &amp;=e^{y\log(p) + (n-y)\log(1-p) + \log\binom{n}{y}}
\end{align*}\]</span>
However, this probability mass function is not quite in one-parameter exponential family form. Note that there are two terms in the exponent which consist of a product of functions of <span class="math inline">\(y\)</span> and <span class="math inline">\(p\)</span>. So more simplification is in order:</p>
<p><span class="math display">\[\begin{equation*}
P(Y=y) = e^{y\log\left(\frac{p}{1-p}\right) + n\log(1-p)+ \log\binom{n}{y}}
\end{equation*}\]</span>
Don’t forget to consider the support; we must make sure that the set of possible values for this response is not dependent upon <span class="math inline">\(p\)</span>. For fixed <span class="math inline">\(n\)</span> and any value of <span class="math inline">\(p\)</span>, <span class="math inline">\(0&lt;p&lt;1\)</span>, all integer values from <span class="math inline">\(0\)</span> to <span class="math inline">\(n\)</span> are possible, so the support is indeed independent of <span class="math inline">\(p\)</span>.</p>
<p>The one-parameter exponential family form for binomial responses shows that the canonical link is <span class="math inline">\(\log\left(\frac{p}{1-p}\right)\)</span>. Thus, GLM theory suggests that constructing a model using the logit, the log odds of a score, as a linear function of covariates is a reasonable approach.</p>
</div>
</div>
<div id="case-study-reconstructing-alabama" class="section level2">
<h2><span class="header-section-number">6.5</span> Case Study: Reconstructing Alabama</h2>
<p>This case study demonstrates how wide-ranging applications of statistics can be. Many would not associate statistics with historical research, but this case study shows that it can be done. U.S. Census data from 1870 helped historian Michael Fitzgerald of St. Olaf College gain insight into important questions about how railroads were supported during the Reconstruction Era.</p>
<p>In a paper entitled “Reconstructing Alabama: Reconstruction Era Demographic and Statistical Research,” Ben Bayer performs an analysis of data from 1870 to explain factors that influence voting on referendums related to railroad subsidies <span class="citation">(Bayer and Fitzgerald <a href="#ref-Bayer2011" role="doc-biblioref">2011</a>)</span>. Positive votes are hypothesized to be inversely proportional to the distance a voter is from the proposed railroad, but the racial composition of a community (as measured by the percentage of blacks) is hypothesized to be associated with voting behavior as well. Separate analyses of three counties in Alabama—Hale, Clarke, and Dallas—were performed; we discuss Hale County here. This example differs from the soccer example in that it includes continuous covariates. Was voting on railroad referenda related to distance from the proposed railroad line and the racial composition of a community?</p>
<div id="data-organization-3" class="section level3">
<h3><span class="header-section-number">6.5.1</span> Data Organization</h3>
<p>The unit of observation for this data is a community in Hale County. We will focus on the following variables from <code>RR_Data_Hale.csv</code> collected for each community (see Table <a href="ch-logreg.html#tab:table2chp6">6.2</a>):</p>
<ul>
<li><p><code>pctBlack</code> = the percentage of blacks in the community</p></li>
<li><p><code>distance</code> = the distance, in miles, the proposed railroad is from the community</p></li>
<li><p><code>YesVotes</code> = the number of “Yes” votes in favor of the proposed railroad line (our primary response variable)</p></li>
<li><p><code>NumVotes</code> = total number of votes cast in the election</p></li>
</ul>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:table2chp6">Table 6.2: </span>Sample of the data for the Hale County, Alabama, railroad subsidy vote.
</caption>
<thead>
<tr>
<th style="text-align:left;">
community
</th>
<th style="text-align:left;">
pctBlack
</th>
<th style="text-align:right;">
distance
</th>
<th style="text-align:right;">
YesVotes
</th>
<th style="text-align:right;">
NumVotes
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Carthage
</td>
<td style="text-align:left;">
58.4
</td>
<td style="text-align:right;">
17
</td>
<td style="text-align:right;">
61
</td>
<td style="text-align:right;">
110
</td>
</tr>
<tr>
<td style="text-align:left;">
Cederville
</td>
<td style="text-align:left;">
92.4
</td>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
15
</td>
</tr>
<tr>
<td style="text-align:left;">
Greensboro
</td>
<td style="text-align:left;">
59.4
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1790
</td>
<td style="text-align:right;">
1804
</td>
</tr>
<tr>
<td style="text-align:left;">
Havana
</td>
<td style="text-align:left;">
58.4
</td>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
16
</td>
<td style="text-align:right;">
68
</td>
</tr>
</tbody>
</table>
</div>
<div id="exploratory-analyses" class="section level3">
<h3><span class="header-section-number">6.5.2</span> Exploratory Analyses</h3>
<p>We first look at a coded scatterplot to see our data. Figure <a href="ch-logreg.html#fig:coded">6.2</a> portrays the relationship between <code>distance</code> and <code>pctBlack</code> coded by the <code>InFavor</code> status (whether a community supported the referendum with over 50% Yes votes). From this scatterplot, we can see that all of the communities in favor of the railroad referendum are over 55% black, and all of those opposed are 7 miles or farther from the proposed line. The overall percentage of voters in Hale County in favor of the railroad is 87.9%.</p>
<div class="figure" style="text-align: center"><span id="fig:coded"></span>
<img src="bookdown-BeyondMLR_files/figure-html/coded-1.png" alt=" Scatterplot of distance from a proposed rail line and percent black in the community coded by whether the community was in favor of the referendum or not." width="60%" />
<p class="caption">
Figure 6.2:  Scatterplot of distance from a proposed rail line and percent black in the community coded by whether the community was in favor of the referendum or not.
</p>
</div>
<p>Recall that a model with two covariates has the form:</p>
<p><span class="math display">\[\log(\textrm{odds}) = \log\left(\frac{p}{1-p}\right) = \beta_0+\beta_1X_1+\beta_2X_2.\]</span>
where <span class="math inline">\(p\)</span> is the proportion of Yes votes in a community. In logistic regression, we expect the logits to be a linear function of <span class="math inline">\(X\)</span>, the predictors. To assess the linearity assumption, we construct <strong>empirical logit plots</strong>,  where “empirical” means “based on sample data.” Empirical logits are computed for each community by taking <span class="math inline">\(\log\left(\frac{\textrm{number of successes}}{\textrm{number of failures}}\right)\)</span>. In Figure <a href="ch-logreg.html#fig:emplogits">6.3</a>, we see that the plot of empirical logits versus distance produces a plot that looks linear, as needed for the logistic regression assumption. In contrast, the empirical logits by percent black reveal that Greensboro deviates quite a bit from the otherwise linear pattern; this suggests that Greensboro is an outlier and possibly an influential point. Greensboro has 99.2% voting yes, with only 59.4% black.</p>
<div class="figure" style="text-align: center"><span id="fig:emplogits"></span>
<img src="bookdown-BeyondMLR_files/figure-html/emplogits-1.png" alt="Empirical logit plots for the Railroad Referendum data." width="60%" />
<p class="caption">
Figure 6.3: Empirical logit plots for the Railroad Referendum data.
</p>
</div>
<p>In addition to examining how the response correlates with the predictors, it is a good idea to determine whether the predictors correlate with one another. Here, the correlation between distance and percent black is negative and moderately strong with <span class="math inline">\(r = -0.49\)</span>. We’ll watch to see if the correlation affects the stability of our odds ratio estimates.</p>
</div>
<div id="initial-models-1" class="section level3">
<h3><span class="header-section-number">6.5.3</span> Initial Models</h3>
<p>The first model includes only one covariate, distance.</p>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb117-1"><a href="ch-logreg.html#cb117-1"></a><span class="co"># Model with just distance</span></span>
<span id="cb117-2"><a href="ch-logreg.html#cb117-2"></a>model.HaleD &lt;-<span class="st"> </span><span class="kw">glm</span>(<span class="kw">cbind</span>(YesVotes, NumVotes <span class="op">-</span><span class="st"> </span>YesVotes) <span class="op">~</span></span>
<span id="cb117-3"><a href="ch-logreg.html#cb117-3"></a><span class="st">    </span>distance, <span class="dt">family =</span> binomial, <span class="dt">data =</span> rrHale.df)</span>
<span id="cb117-4"><a href="ch-logreg.html#cb117-4"></a><span class="co"># alternative expression</span></span>
<span id="cb117-5"><a href="ch-logreg.html#cb117-5"></a>model.HaleD.alt &lt;-<span class="st"> </span><span class="kw">glm</span>(YesVotes <span class="op">/</span><span class="st"> </span>NumVotes <span class="op">~</span><span class="st"> </span>distance, </span>
<span id="cb117-6"><a href="ch-logreg.html#cb117-6"></a>    <span class="dt">weights =</span> NumVotes, <span class="dt">family =</span> binomial, <span class="dt">data =</span> rrHale.df)</span></code></pre></div>
<pre><code>##             Estimate Std. Error z value   Pr(&gt;|z|)
## (Intercept)   3.3093    0.11313   29.25 4.268e-188
## distance     -0.2876    0.01302  -22.08 4.447e-108</code></pre>
<pre><code>##  Residual deviance =  318.4  on  9 df 
##  Dispersion parameter =  1</code></pre>
<p>Our estimated binomial regression model is:</p>
<p><span class="math display">\[\log\left(\frac{\hat{p}_i}{1-\hat{p}_i}\right)=3.309-0.288 \textrm{distance}_i\]</span>
where <span class="math inline">\(\hat{p}_i\)</span> is the estimated proportion of Yes votes in community <span class="math inline">\(i\)</span>. The estimated odds ratio for distance, that is the exponentiated coefficient for distance, in this model is <span class="math inline">\(e^{-0.288}=0.750\)</span>. It can be interpreted as follows: for each additional mile from the proposed railroad, the support (odds of a Yes vote) declines by 25.0%.</p>
<p>The covariate <code>pctBlack</code> is then added to the first model.</p>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb120-1"><a href="ch-logreg.html#cb120-1"></a>model.HaleBD &lt;-<span class="st"> </span><span class="kw">glm</span>(<span class="kw">cbind</span>(YesVotes, NumVotes <span class="op">-</span><span class="st"> </span>YesVotes) <span class="op">~</span></span>
<span id="cb120-2"><a href="ch-logreg.html#cb120-2"></a><span class="st">  </span>distance <span class="op">+</span><span class="st"> </span>pctBlack, <span class="dt">family =</span> binomial, <span class="dt">data =</span> rrHale.df)</span></code></pre></div>
<pre><code>##             Estimate Std. Error z value   Pr(&gt;|z|)
## (Intercept)  4.22202   0.296963  14.217  7.155e-46
## distance    -0.29173   0.013100 -22.270 7.236e-110
## pctBlack    -0.01323   0.003897  -3.394  6.881e-04</code></pre>
<pre><code>##  Residual deviance =  307.2  on  8 df 
##  Dispersion parameter =  1</code></pre>
<p>Despite the somewhat strong negative correlation between percent black and distance, the estimated odds ratio for distance remains approximately the same in this new model (OR <span class="math inline">\(= e^{-0.29} = 0.747\)</span>); controlling for percent black does little to change our estimate of the effect of distance. For each additional mile from the proposed railroad, odds of a Yes vote declines by 25.3% after adjusting for the racial composition of a community. We also see that, for a fixed distance from the proposed railroad, the odds of a Yes vote declines by 1.3% (OR <span class="math inline">\(= e^{-.0132} = .987\)</span>) for each additional percent black in the community.</p>
</div>
<div id="sec-logisticInf" class="section level3">
<h3><span class="header-section-number">6.5.4</span> Tests for Significance of Model Coefficients</h3>
<p>Do we have statistically significant evidence that support for the railroad referendum decreases with higher proportions of black residents in a community, after accounting for the distance a community is from the railroad line? As discussed in Section <a href="ch-poissonreg.html#cs-philippines">4.4</a> with Poisson regression, there are two primary approaches to testing significance of model coefficients: <strong>Drop-in-deviance test to compare models</strong>  and <strong>Wald test for a single coefficient</strong>. </p>
<p>With our larger model given by <span class="math inline">\(\log\left(\frac{p_i}{1-p_i}\right) = \beta_0+\beta_1\textrm{distance}_i+\beta_2\textrm{pctBlack}_i\)</span>, the Wald test produces a highly significant p-value (<span class="math inline">\(Z=\frac{-0.0132}{0.0039}= -3.394\)</span>, <span class="math inline">\(p=.00069\)</span>) indicating significant evidence that support for the railroad referendum decreases with higher proportions of black residents in a community, after adjusting for the distance a community is from the railroad line.</p>
<p>The drop-in-deviance test would compare the larger model above to the reduced model <span class="math inline">\(\log\left(\frac{p_i}{1-p_i}\right) = \beta_0+\beta_1\textrm{distance}_i\)</span> by comparing residual deviances from the two models.</p>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb123-1"><a href="ch-logreg.html#cb123-1"></a>drop_in_dev &lt;-<span class="st"> </span><span class="kw">anova</span>(model.HaleD, model.HaleBD, <span class="dt">test =</span> <span class="st">&quot;Chisq&quot;</span>)</span></code></pre></div>
<pre><code>  ResidDF ResidDev Deviance Df      pval
1       9    318.4       NA NA        NA
2       8    307.2    11.22  1 0.0008083</code></pre>
<p>The drop-in-deviance test statistic is <span class="math inline">\(318.44 - 307.22 = 11.22\)</span> on <span class="math inline">\(9 - 8 = 1\)</span> df, producing a p-value of .00081, in close agreement with the Wald test.</p>
<p>A third approach to determining significance of <span class="math inline">\(\beta_2\)</span> would be to generate a 95% confidence interval and then checking if 0 falls within the interval or, equivalently, if 1 falls within a 95% confidence interval for <span class="math inline">\(e^{\beta_2}.\)</span> The next section describes two approaches to producing a confidence interval for coefficients in logistic regression models.</p>
</div>
<div id="confidence-intervals-for-model-coefficients" class="section level3">
<h3><span class="header-section-number">6.5.5</span> Confidence Intervals for Model Coefficients</h3>
<p>Since the Wald statistic follows a normal distribution with <span class="math inline">\(n\)</span> large, we could generate a Wald-type (normal-based) confidence interval  for <span class="math inline">\(\beta_2\)</span> using:</p>
<p><span class="math display">\[\hat\beta_2 \pm 1.96\cdot\textrm{SE}(\hat\beta_2)\]</span>
and then exponentiating endpoints if we prefer a confidence interval for the odds ratio <span class="math inline">\(e^{\beta_2}\)</span>. In this case,</p>
<p><span class="math display">\[\begin{align*}
95\% \textrm{ CI for } \beta_2 &amp;= \hat{\beta}_2 \pm 1.96 \cdot \textrm{SE}(\hat{\beta}_2) \\
                               &amp;= -0.0132 \pm 1.96 \cdot 0.0039 \\
                               &amp;= -0.0132 \pm 0.00764 \\
                               &amp;= (-0.0208, -0.0056) \\
95\% \textrm{ CI for } e^{\beta_2} &amp;= (e^{-0.0208}, e^{-0.0056}) \\
                                   &amp;= (.979, .994) \\
95\% \textrm{ CI for } e^{10\beta_2} &amp;= (e^{-0.208}, e^{-0.056}) \\
                                      &amp;= (.812, .946)
\end{align*}\]</span></p>
<p>Thus, we can be 95% confident that a 10% increase in the proportion of black residents is associated with a 5.4% to 18.8% decrease in the odds of a Yes vote for the railroad referendum after controlling for distance. This same relationship could be expressed as (a) between a 0.6% and a 2.1% decrease in odds for each 1% increase in the black population, or (b) between a 5.7% (<span class="math inline">\(1/e^{-.056}\)</span>) and a 23.1% (<span class="math inline">\(1/e^{-.208}\)</span>) increase in odds for each 10% decrease in the black population, after adjusting for distance. Of course, with <span class="math inline">\(n=11\)</span>, we should be cautious about relying on a Wald-type interval in this example.</p>
<p>Another approach available in R is the <strong>profile likelihood method</strong>,  similar to Section <a href="ch-poissonreg.html#cs-philippines">4.4</a>.</p>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb125-1"><a href="ch-logreg.html#cb125-1"></a><span class="kw">exp</span>(<span class="kw">confint</span>(model.HaleBD))</span></code></pre></div>
<pre><code>              2.5 %   97.5 %
(Intercept) 38.2285 122.6116
distance     0.7276   0.7660
pctBlack     0.9794   0.9945</code></pre>
<p>In the model with <code>distance</code> and <code>pctBlack</code>, the profile likelihood 95% confidence interval for <span class="math inline">\(e^{\beta_2}\)</span> is (.979, .994), which is approximately equal to the Wald-based interval despite the small sample size. We can also confirm the statistically significant association between percent black and odds of voting Yes (after controlling for distance), because 1 is not a plausible value of <span class="math inline">\(e^{\beta_2}\)</span> (where an odds ratio of 1 would imply that the odds of voting Yes do not change with percent black).</p>
</div>
<div id="testing-for-goodness-of-fit" class="section level3">
<h3><span class="header-section-number">6.5.6</span> Testing for Goodness-of-Fit</h3>
<p>As in Section <a href="ch-poissonreg.html#sec-PoisGOF">4.4.9</a>, we can evaluate the goodness-of-fit for our model by comparing the residual deviance (307.22) to a <span class="math inline">\(\chi^2\)</span> distribution with <span class="math inline">\(n-p\)</span> (8) degrees of freedom.</p>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb127-1"><a href="ch-logreg.html#cb127-1"></a><span class="dv">1</span><span class="op">-</span><span class="kw">pchisq</span>(<span class="fl">307.2173</span>, <span class="dv">8</span>)  <span class="co"># Goodness-of-fit test</span></span></code></pre></div>
<pre><code>[1] 0</code></pre>
<p>The model with <code>pctBlack</code> and <code>distance</code> has statistically significant evidence of lack-of-fit (<span class="math inline">\(p&lt;.001\)</span>).</p>
<p>Similar to the Poisson regression models, this lack-of-fit  could result from (a) missing covariates, (b) outliers, or (c) overdispersion. We will first attempt to address (a) by fitting a model with an interaction between distance and percent black, to determine whether the effect of racial composition differs based on how far a community is from the proposed railroad.</p>
<div class="sourceCode" id="cb129"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb129-1"><a href="ch-logreg.html#cb129-1"></a>model.HaleBxD &lt;-<span class="st"> </span><span class="kw">glm</span>(<span class="kw">cbind</span>(YesVotes, NumVotes <span class="op">-</span><span class="st"> </span>YesVotes) <span class="op">~</span></span>
<span id="cb129-2"><a href="ch-logreg.html#cb129-2"></a><span class="st">  </span>distance <span class="op">+</span><span class="st"> </span>pctBlack <span class="op">+</span><span class="st"> </span>distance<span class="op">:</span>pctBlack, </span>
<span id="cb129-3"><a href="ch-logreg.html#cb129-3"></a>  <span class="dt">family =</span> binomial, <span class="dt">data =</span> rrHale.df)</span></code></pre></div>
<pre><code>##                    Estimate Std. Error z value
## (Intercept)        7.550902  0.6383697  11.828
## distance          -0.614005  0.0573808 -10.701
## pctBlack          -0.064731  0.0091723  -7.057
## distance:pctBlack  0.005367  0.0008984   5.974
##                    Pr(&gt;|z|)
## (Intercept)       2.783e-32
## distance          1.012e-26
## pctBlack          1.698e-12
## distance:pctBlack 2.321e-09</code></pre>
<pre><code>##  Residual deviance =  274.2  on  7 df 
##  Dispersion parameter =  1</code></pre>
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb132-1"><a href="ch-logreg.html#cb132-1"></a>drop_in_dev &lt;-<span class="st"> </span><span class="kw">anova</span>(model.HaleBD, model.HaleBxD, </span>
<span id="cb132-2"><a href="ch-logreg.html#cb132-2"></a>                     <span class="dt">test =</span> <span class="st">&quot;Chisq&quot;</span>)</span></code></pre></div>
<pre><code>  ResidDF ResidDev Deviance Df      pval
1       8    307.2       NA NA        NA
2       7    274.2    32.98  1 9.294e-09</code></pre>
<p>We have statistically significant evidence (Wald test: <span class="math inline">\(Z = 5.974, p&lt;.001\)</span>; Drop-in-deviance test: <span class="math inline">\(\chi^2=32.984, p&lt;.001\)</span>) that the effect of the proportion of the community that is black on the odds of voting Yes depends on the distance of the community from the proposed railroad.</p>
<p>To interpret the interaction coefficient in context, we will compare two cases: one where a community is right on the proposed railroad (<code>distance</code> = 0), and the other where the community is 15 miles away (<code>distance</code> = 15). The significant interaction implies that the effect of <code>pctBlack</code> should differ in these two cases. In the first case, the coefficient for <code>pctBlack</code> is -0.0647, while in the second case, the relevant coefficient is <span class="math inline">\(-0.0647+15(.00537) = 0.0158\)</span>. Thus, for a community right on the proposed railroad, a 1% increase in percent black is associated with a 6.3% (<span class="math inline">\(e^{-.0647}=.937\)</span>) decrease in the odds of voting Yes, while for a community 15 miles away, a 1% increase in percent black is associated with a (<span class="math inline">\(e^{.0158}=1.016\)</span>) 1.6% <em>increase</em> in the odds of voting Yes. A significant interaction term doesn’t always imply a change in the direction of the association, but it does here.</p>
<p>Because our interaction model still exhibits lack-of-fit (residual deviance of 274.23 on just 7 df), and because we have used the covariates at our disposal, we will assess this model for potential outliers and overdispersion by examining the model’s residuals.</p>
</div>
<div id="residuals-for-binomial-regression" class="section level3">
<h3><span class="header-section-number">6.5.7</span> Residuals for Binomial Regression</h3>
<p>With LLSR, residuals were used to assess model assumptions and identify outliers. For binomial regression, two different types of residuals are typically used. One residual, the <strong>Pearson residual</strong>,  has a form similar to that used with LLSR. Specifically, the Pearson residual is calculated using:</p>
<p><span class="math display">\[\begin{equation*}
\textrm{Pearson residual}_i = \frac{\textrm{actual count}-\textrm{predicted count}}{\textrm{SD of count}} =
\frac{Y_i-m_i\hat{p_i}}{\sqrt{m_i\hat{p_i}(1-\hat{p_i})}}
\end{equation*}\]</span>
where <span class="math inline">\(m_i\)</span> is the number of trials for the <span class="math inline">\(i^{th}\)</span> observation and <span class="math inline">\(\hat{p}_i\)</span> is the estimated probability of success for that same observation.</p>
<p>A <strong>deviance residual</strong>  is an alternative residual for binomial regression based on the discrepancy between the observed values and those estimated using the likelihood.
A deviance residual can be calculated for each observation using:</p>
<p><span class="math display">\[\begin{equation*}
\textrm{d}_i = 
\textrm{sign}(Y_i-m_i\hat{p_i})\sqrt{2[Y_i \log\left(\frac{Y_i}{m_i \hat{p_i}}\right)+
(m_i - Y_i) \log\left(\frac{m_i - Y_i}{m_i - m_i \hat{p_i}}\right)]}
\end{equation*}\]</span></p>
<p>When the number of trials is large for all of the observations and the models are appropriate, both sets of residuals should follow a standard normal distribution.</p>
<p>The sum of the individual deviance residuals is referred to as the <strong>deviance</strong> or <strong>residual deviance</strong>.  The residual deviance is used to assess the model. As the name suggests, a model with a small deviance is preferred. In the case of binomial regression, when the denominators, <span class="math inline">\(m_i\)</span>, are large and a model fits, the residual deviance follows a <span class="math inline">\(\chi^2\)</span> distribution with <span class="math inline">\(n-p\)</span> degrees of freedom (the residual degrees of freedom). Thus for a good fitting model the residual deviance should be approximately equal to its corresponding degrees of freedom. When binomial data meets these conditions, the deviance can be used for a goodness-of-fit test. The p-value for lack-of-fit is the proportion of values from a <span class="math inline">\(\chi_{n-p}^2\)</span> distribution that are greater than the observed residual deviance.</p>
<p>We begin a residual analysis of our interaction model by plotting the residuals against the fitted values in Figure <a href="ch-logreg.html#fig:resid">6.4</a>. This kind of plot for binomial regression would produce two linear trends with similar negative slopes if there were equal sample sizes <span class="math inline">\(m_i\)</span> for each observation.</p>
<div class="figure" style="text-align: center"><span id="fig:resid"></span>
<img src="bookdown-BeyondMLR_files/figure-html/resid-1.png" alt="Fitted values by residuals for the interaction model for the Railroad Referendum data." width="60%" />
<p class="caption">
Figure 6.4: Fitted values by residuals for the interaction model for the Railroad Referendum data.
</p>
</div>
<p>From this residual plot, Greensboro does not stand out as an outlier. If it did, we could remove Greensboro and refit our interaction model, checking to see if model coefficients changed in a noticeable way. Instead, we will continue to include Greensboro in our modeling efforts. Because the large residual deviance cannot be explained by outliers, and given we have included all of the covariates at hand as well as an interaction term, the observed binomial counts are likely overdispersed. This means that they exhibit more variation than the model would suggest, and we must consider ways to handle this overdispersion.</p>
</div>
<div id="sec-logOverdispersion" class="section level3">
<h3><span class="header-section-number">6.5.8</span> Overdispersion</h3>
<p>Similar to Poisson regression, we can adjust for overdispersion  in binomial regression. With overdispersion there is <strong>extra-binomial variation</strong>,  so the actual variance will be greater than the variance of a binomial variable, <span class="math inline">\(np(1-p)\)</span>. One way to adjust for overdispersion is to estimate a multiplier (dispersion parameter), <span class="math inline">\(\hat{\phi}\)</span>, for the variance that will inflate it and reflect the reduction in the amount of information we would otherwise have with independent observations. We used a similar approach to adjust for overdispersion in a Poisson regression model in Section <a href="ch-poissonreg.html#sec-overdispPois">4.9</a>, and we will use the same estimate here: <span class="math inline">\(\hat\phi=\frac{\sum(\textrm{Pearson residuals})^2}{n-p}\)</span>.</p>
<p>When overdispersion is adjusted for in this way, we can no longer use maximum likelihood to fit our regression model; instead we use a quasilikelihood approach.  Quasilikelihood is similar to likelihood-based inference, but because the model uses the dispersion parameter, it is not a binomial model with a true likelihood (we call it <strong>quasibinomial</strong>).  R offers quasilikelihood as an option when model fitting. The quasilikelihood approach will yield the same coefficient point estimates as maximum likelihood; however, the variances will be larger in the presence of overdispersion (assuming <span class="math inline">\(\phi&gt;1\)</span>). We will see other ways in which to deal with overdispersion and clusters in the remaining chapters in the book, but the following describes how overdispersion is accounted for using <span class="math inline">\(\hat{\phi}\)</span>:
</p>
<p><strong>Summary: accounting for overdispersion</strong></p>
<ul>
<li>Use the dispersion parameter <span class="math inline">\(\hat\phi=\frac{\sum(\textrm{Pearson residuals})^2}{n-p}\)</span> to inflate standard errors of model coefficients.</li>
<li>Wald test statistics: multiply the standard errors by <span class="math inline">\(\sqrt{\hat{\phi}}\)</span> so that <span class="math inline">\(\textrm{SE}_\textrm{Q}(\hat\beta)=\sqrt{\hat\phi}\cdot\textrm{SE}(\hat\beta)\)</span> and conduct tests using the <span class="math inline">\(t\)</span>-distribution.</li>
<li>Confidence intervals use the adjusted standard errors and multiplier based on <span class="math inline">\(t\)</span>, so they are thereby wider: <span class="math inline">\(\hat\beta \pm t_{n-p} \cdot \textrm{SE}_\textrm{Q}(\hat\beta)\)</span>.</li>
<li>Drop-in-deviance test statistic comparing Model 1 (larger model with <span class="math inline">\(p\)</span> parameters) to Model 2 (smaller model with <span class="math inline">\(q&lt;p\)</span> parameters) is <span class="math inline">\(F = \frac{1}{\hat\phi} \cdot \frac{D_2 - D_1}{p-q}\)</span> where <span class="math inline">\(D_1\)</span> and <span class="math inline">\(D_2\)</span> are the residual deviances for models 1 and 2, respectively, and <span class="math inline">\(p-q\)</span> is the difference in the number of parameters for the two models. Note that both <span class="math inline">\(D_2-D_1\)</span> and <span class="math inline">\(p-q\)</span> are positive. This test statistic is compared to an F-distribution with <span class="math inline">\(p-q\)</span> and <span class="math inline">\(n-p\)</span> degrees of freedom.</li>
</ul>
<p>Output for a model which adjusts our interaction model for overdispersion appears below, where <span class="math inline">\(\hat{\phi}=51.6\)</span> is used to adjust the standard errors for the coefficients and the drop-in-deviance tests during model building. Standard errors will be inflated by a factor of <span class="math inline">\(\sqrt{51.6}=7.2\)</span>. As a result, there are no significant terms in the adjusted interaction model below.</p>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb134-1"><a href="ch-logreg.html#cb134-1"></a>model.HaleBxDq &lt;-<span class="st"> </span><span class="kw">glm</span>(<span class="kw">cbind</span>(YesVotes, NumVotes <span class="op">-</span><span class="st"> </span>YesVotes) <span class="op">~</span></span>
<span id="cb134-2"><a href="ch-logreg.html#cb134-2"></a><span class="st">  </span>distance <span class="op">+</span><span class="st"> </span>pctBlack <span class="op">+</span><span class="st"> </span>distance<span class="op">:</span>pctBlack, </span>
<span id="cb134-3"><a href="ch-logreg.html#cb134-3"></a>  <span class="dt">family =</span> quasibinomial, <span class="dt">data =</span> rrHale.df)</span></code></pre></div>
<pre><code>##                    Estimate Std. Error t value
## (Intercept)        7.550902   4.585464  1.6467
## distance          -0.614005   0.412171 -1.4897
## pctBlack          -0.064731   0.065885 -0.9825
## distance:pctBlack  0.005367   0.006453  0.8316
##                   Pr(&gt;|t|)
## (Intercept)         0.1436
## distance            0.1799
## pctBlack            0.3586
## distance:pctBlack   0.4331</code></pre>
<pre><code>##  Residual deviance =  274.2  on  7 df 
##  Dispersion parameter =  51.6</code></pre>
<p>We therefore remove the interaction term and refit the model, adjusting for the extra-binomial variation that still exists.</p>
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb137-1"><a href="ch-logreg.html#cb137-1"></a>model.HaleBDq &lt;-<span class="st"> </span><span class="kw">glm</span>(<span class="kw">cbind</span>(YesVotes, NumVotes <span class="op">-</span><span class="st"> </span>YesVotes) <span class="op">~</span></span>
<span id="cb137-2"><a href="ch-logreg.html#cb137-2"></a><span class="st">  </span>distance <span class="op">+</span><span class="st"> </span>pctBlack, </span>
<span id="cb137-3"><a href="ch-logreg.html#cb137-3"></a>  <span class="dt">family =</span> quasibinomial, <span class="dt">data =</span> rrHale.df)</span></code></pre></div>
<pre><code>##             Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept)  4.22202    1.99031  2.1213  0.06669
## distance    -0.29173    0.08780 -3.3228  0.01050
## pctBlack    -0.01323    0.02612 -0.5064  0.62620</code></pre>
<pre><code>##  Residual deviance =  307.2  on  8 df 
##  Dispersion parameter =  44.92</code></pre>
<p>By removing the interaction term and using the overdispersion parameter, we see that distance is significantly associated with support, but percent black is no longer significant after adjusting for distance.</p>
<p>Because quasilikelihood methods do not change estimated coefficients, we still estimate a 25% decline <span class="math inline">\((1-e^{-0.292})\)</span> in support for each additional mile from the proposed railroad (odds ratio of .75).</p>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb140-1"><a href="ch-logreg.html#cb140-1"></a><span class="kw">exp</span>(<span class="kw">confint</span>(model.HaleBDq))</span></code></pre></div>
<pre><code>             2.5 %   97.5 %
(Intercept) 1.3609 5006.722
distance    0.6091    0.871
pctBlack    0.9366    1.044</code></pre>
<p>While we previously found a 95% confidence interval for the odds ratio associated with distance of (.728, .766), our confidence interval is now much wider: (.609, .871). Appropriately accounting for overdispersion has changed both the significance of certain terms and the precision of our coefficient estimates.</p>
</div>
<div id="summary-1" class="section level3">
<h3><span class="header-section-number">6.5.9</span> Summary</h3>
<p>We began by fitting a logistic regression model with <code>distance</code> alone. Then we added the covariate <code>pctBlack</code>, and the Wald-type test and the drop-in-deviance test both provided strong support for the addition of <code>pctBlack</code> to the model. The model with <code>distance</code> and <code>pctBlack</code> had a large residual deviance suggesting an ill-fitted model. When we looked at the residuals, we saw that Greensboro is an extreme observation. Models without Greensboro were fitted and compared to our initial models. Seeing no appreciable improvement or differences with Greensboro removed, we left it in the model. There remained a large residual deviance so we attempted to account for it by using an estimated dispersion parameter similar to Section <a href="ch-poissonreg.html#sec-overdispPois">4.9</a> with Poisson regression. The final model included distance and percent black, although percent black was no longer significant after adjusting for overdispersion.</p>
</div>
</div>
<div id="linear-least-squares-vs.-binomial-regression" class="section level2">
<h2><span class="header-section-number">6.6</span> Linear Least Squares  vs. Binomial Regression </h2>
<p><span class="math display">\[\begin{gather*}
\underline{\textrm{Response}} \\
\mathbf{LLSR:}\textrm{ normal} \\
\mathbf{Binomial\ Regression:}\textrm{ number of successes in n trials} \\
\textrm{ } \\
\underline{\textrm{Variance}} \\
\mathbf{LLSR:}\textrm{ equal for each level of}\ X \\
\mathbf{Binomial\ Regression:}\ np(1-p)\textrm{ for each level of}\ X \\
\textrm{ } \\
\underline{\textrm{Model Fitting}} \\
\mathbf{LLSR:}\ \mu=\beta_0+\beta_1x \textrm{ using Least Squares}\\
\mathbf{Binomial\ Regression:}\ \log\left(\frac{p}{1-p}\right)=\beta_0+\beta_1x \textrm{ using Maximum Likelihood}\\
\textrm{ } \\
\underline{\textrm{EDA}} \\
\mathbf{LLSR:}\textrm{ plot $X$ vs. $Y$; add line} \\
\mathbf{Binomial\ Regression:}\textrm{ find $\log(\textrm{odds})$ for several subgroups; plot vs. $X$} \\
\end{gather*}\]</span></p>
<p><span class="math display">\[\begin{gather*}
\underline{\textrm{Comparing Models}} \\
\mathbf{LLSR:}\textrm{ extra sum of squares F-tests; AIC/BIC} \\
\mathbf{Binomial\ Regression:}\textrm{ drop-in-deviance tests; AIC/BIC} \\
\textrm{ } \\
\underline{\textrm{Interpreting Coefficients}} \\
\mathbf{LLSR:}\ \beta_1=\textrm{ change in mean response for unit change in $X$} \\
\mathbf{Binomial\ Regression:}\ e^{\beta_1}=\textrm{ percent change in odds for unit change in $X$} 
\end{gather*}\]</span></p>
</div>
<div id="case-study-trying-to-lose-weight" class="section level2">
<h2><span class="header-section-number">6.7</span> Case Study: Trying to Lose Weight</h2>
<p>The final case study uses individual-specific information so that our response, rather than the number of successes out of some number of trials, is simply a binary variable taking on values of 0 or 1 (for failure/success, no/yes, etc.). This type of problem—<strong>binary logistic regression</strong>—is exceedingly common in practice.  Here we examine characteristics of young people who are trying to lose weight. The prevalence of obesity among U.S. youth suggests that wanting to lose weight is sensible and desirable for some young people such as those with a high body mass index (BMI). On the flip side, there are young people who do not need to lose weight but make ill-advised attempts to do so nonetheless. A multitude of studies on weight loss focus specifically on youth and propose a variety of motivations for the young wanting to lose weight; athletics and the media are two commonly cited sources of motivation for losing weight for young people.</p>
<p>Sports have been implicated as a reason for young people wanting to shed pounds, but not all studies are consistent with this idea. For example, a study by <span class="citation">Martinsen et al. (<a href="#ref-Martinsen2009" role="doc-biblioref">2009</a>)</span> reported that, despite preconceptions to the contrary, there was a higher rate of self-reported eating disorders among controls (non-elite athletes) as opposed to elite athletes. Interestingly, the kind of sport was not found to be a factor, as participants in leanness sports (for example, distance running, swimming, gymnastics, dance, and diving) did not differ in the proportion with eating disorders when compared to those in non-leanness sports. So, in our analysis, we will not make a distinction between different sports.</p>
<p>Other studies suggest that mass media is the culprit. They argue that students’ exposure to unrealistically thin celebrities may provide unhealthy motivation for some, particularly young women, to try to slim down. An examination and analysis of a large number of related studies (referred to as a <strong>meta-analysis</strong>) <span class="citation">(Grabe, Hyde, and Ward <a href="#ref-Grabe2008" role="doc-biblioref">2008</a>)</span> found a strong relationship between exposure to mass media and the amount of time that adolescents spend talking about what they see in the media, deciphering what it means, and figuring out how they can be more like the celebrities.</p>
<p>We are interested in the following questions: Are the odds that young females report trying to lose weight greater than the odds that males do? Is increasing BMI associated with an interest in losing weight, regardless of sex? Does sports participation increase the desire to lose weight? Is media exposure associated with more interest in losing weight?</p>
<p>We have a sample of 500 teens from data collected in 2009 through the U.S. Youth Risk Behavior Surveillance System (YRBSS) <span class="citation">(Centers for Disease Control and Prevention <a href="#ref-YRBS2009" role="doc-biblioref">2009</a>)</span>. The YRBSS is an annual national school-based survey conducted by the Centers for Disease Control and Prevention (CDC) and state, territorial, and local education and health agencies and tribal governments. More information on this survey can be found <a href="http://www.cdc.gov/HealthyYouth/yrbs/index.htm">here</a>.</p>
<div id="data-organization-4" class="section level3">
<h3><span class="header-section-number">6.7.1</span> Data Organization</h3>
<p>Here are the three questions from the YRBSS we use for our investigation:</p>
<p>Q66. Which of the following are you trying to do about your weight?</p>
<ul>
<li>A. Lose weight</li>
<li>B. Gain weight</li>
<li>C. Stay the same weight</li>
<li>D. I am not trying to do anything about my weight</li>
</ul>
<p>Q81. On an average school day, how many hours do you watch TV?</p>
<ul>
<li>A. I do not watch TV on an average school day</li>
<li>B. Less than 1 hour per day</li>
<li>C. 1 hour per day</li>
<li>D. 2 hours per day</li>
<li>E. 3 hours per day</li>
<li>F. 4 hours per day</li>
<li>G. 5 or more hours per day</li>
</ul>
<p>Q84. During the past 12 months, on how many sports teams did you play? (Include any teams run by your school or community groups.)</p>
<ul>
<li>A. 0 teams</li>
<li>B. 1 team</li>
<li>C. 2 teams</li>
<li>D. 3 or more teams</li>
</ul>
<p>Answers to Q66 are used to define our response variable: Y = 1 corresponds to “(A) trying to lose weight”, while Y = 0 corresponds to the other non-missing values. Q84 provides information on students’ sports participation and is treated as numerical, 0 through 3, with 3 representing 3 or more. As a proxy for media exposure, we use answers to Q81 as numerical values 0, 0.5, 1, 2, 3, 4, and 5, with 5 representing 5 or more. Media exposure and sports participation are also considered as categorical factors, that is, as variables with distinct levels which can be denoted by indicator variables as opposed to their numerical values.</p>
<p>BMI is included in this study as the percentile for a given BMI for members of the same sex. This facilitates comparisons when modeling with males and females. We will use the terms <em>BMI</em> and <em>BMI percentile</em> interchangeably with the understanding that we are always referring to the percentile.</p>
<p>With our sample, we use only the cases that include all of the data for these four questions. This is referred to as a <strong>complete case analysis</strong>. That brings our sample of 500 to 445. There are limitations of complete case analyses that we address in the Discussion.</p>
</div>
<div id="exploratory-data-analysis-2" class="section level3">
<h3><span class="header-section-number">6.7.2</span> Exploratory Data Analysis</h3>
<p>Nearly half (44.7%) of our sample of 445 youths report that they are trying to lose weight, 48.1% of the sample are females, and 59.3% play on one or more sports teams. Also, 8.8% report that they do not watch any TV on school days, whereas another 13.0% watched 5 or more hours each day. Interestingly, the median BMI percentile for our 445 youths is 68. The most dramatic difference in the proportions of those who are trying to lose weight is by sex; 58% of the females want to lose weight in contrast to only 32% of the males (see Figure <a href="ch-logreg.html#fig:mosaicsexlose">6.5</a>). This provides strong support for the inclusion of a sex term in every model considered.</p>
<div class="figure" style="text-align: center"><span id="fig:mosaicsexlose"></span>
<img src="bookdown-BeyondMLR_files/figure-html/mosaicsexlose-1.png" alt="Weight loss plans vs. sex." width="60%" />
<p class="caption">
Figure 6.5: Weight loss plans vs. sex.
</p>
</div>
<table>
<caption>
<span id="tab:table3chp6">Table 6.3: </span>Mean BMI percentile by sex and desire to lose weight.
</caption>
<thead>
<tr>
<th style="text-align:left;">
Sex
</th>
<th style="text-align:left;">
Weight loss status
</th>
<th style="text-align:left;">
mean BMI percentile
</th>
<th style="text-align:left;">
SD
</th>
<th style="text-align:right;">
n
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Female
</td>
<td style="text-align:left;">
No weight loss
</td>
<td style="text-align:left;">
43.2
</td>
<td style="text-align:left;">
25.8
</td>
<td style="text-align:right;">
89
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
Lose weight
</td>
<td style="text-align:left;">
72.4
</td>
<td style="text-align:left;">
23.0
</td>
<td style="text-align:right;">
125
</td>
</tr>
<tr>
<td style="text-align:left;">
Male
</td>
<td style="text-align:left;">
No weight loss
</td>
<td style="text-align:left;">
58.8
</td>
<td style="text-align:left;">
28.2
</td>
<td style="text-align:right;">
157
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
Lose weight
</td>
<td style="text-align:left;">
85.7
</td>
<td style="text-align:left;">
18.0
</td>
<td style="text-align:right;">
74
</td>
</tr>
</tbody>
</table>
<p>Table <a href="ch-logreg.html#tab:table3chp6">6.3</a> displays the mean BMI of those wanting and not wanting to lose weight for males and females. The mean BMI is greater for those trying to lose weight compared to those not trying to lose weight, regardless of sex. The size of the difference is remarkably similar for the two sexes.</p>
If we consider including a BMI term in our model(s), the logit should be linearly related to BMI. We can investigate this assumption by constructing an empirical logit plot. In order to calculate empirical logits, we first divide our data by sex. Within each sex, we generate 10 groups of equal sizes, the first holding the bottom 10% in BMI percentile for that sex, the second holding the next lowest 10%, etc. Within each group, we calculate the proportion, <span class="math inline">\(\hat{p}\)</span> that reported wanting to lose weight, and then the empirical log odds, <span class="math inline">\(log(\frac{\hat{p}}{1-\hat{p}})\)</span>, that a young person in that group wants to lose weight.
<div class="figure" style="text-align: center"><span id="fig:logitBMIsex"></span>
<img src="bookdown-BeyondMLR_files/figure-html/logitBMIsex-1.png" alt="Empirical logits of trying to lose weight by BMI and sex." width="60%" />
<p class="caption">
Figure 6.6: Empirical logits of trying to lose weight by BMI and sex.
</p>
</div>
<p>Figure <a href="ch-logreg.html#fig:logitBMIsex">6.6</a> presents the empirical logits for the BMI intervals by sex. Both males and females exhibit an increasing linear trend on the logit scale indicating that increasing BMI is associated with a greater desire to lose weight and that modeling log odds as a linear function of BMI is reasonable. The slope for the females appears to be similar to the slope for males, so we do not need to consider an interaction term between BMI and sex in the model.</p>
<div class="figure" style="text-align: center"><span id="fig:mosaicsexsports"></span>
<img src="bookdown-BeyondMLR_files/figure-html/mosaicsexsports-1.png" alt="Weight loss plans vs. sex and sports participation." width="60%" />
<p class="caption">
Figure 6.7: Weight loss plans vs. sex and sports participation.
</p>
</div>
<p>Out of those who play sports, 44% want to lose weight, whereas 46% want to lose weight among those who do not play sports. Figure <a href="ch-logreg.html#fig:mosaicsexsports">6.7</a> compares the proportion of respondents who want to lose weight by their sex and sport participation. The data suggest that sports participation is associated with the same or even a slightly lower desire to lose weight, contrary to what had originally been hypothesized. While the overall levels of those wanting to lose weight differ considerably between the sexes, the differences between those in and out of sports within sex appear to be very small. A term for sports participation or number of teams will be considered, but there is not compelling evidence that an interaction term will be needed.</p>
<p>It was posited that increased exposure to media, here measured as hours of TV daily, is associated with increased desire to lose weight, particularly for females. Overall, the percentage who want to lose weight ranges from 38% of those watching 5 hours of TV per day to 55% among those watching 2 hours daily. There is minimal variation in the proportion wanting to lose weight with both sexes combined. However, we are more interested in differences between the sexes (see Figure <a href="ch-logreg.html#fig:mediaXsex">6.8</a>). We create empirical logits using the proportion of students trying to lose weight for each level of hours spent watching TV daily and look at the trends in the logits separately for males and females. From Figure <a href="ch-logreg.html#fig:logitmediasex">6.9</a>, there does not appear to be a linear relationship for males or females.</p>
<div class="figure" style="text-align: center"><span id="fig:mediaXsex"></span>
<img src="bookdown-BeyondMLR_files/figure-html/mediaXsex-1.png" alt="Weight loss plans vs. daily hours of TV and sex." width="60%" />
<p class="caption">
Figure 6.8: Weight loss plans vs. daily hours of TV and sex.
</p>
</div>
<div class="figure" style="text-align: center"><span id="fig:logitmediasex"></span>
<img src="bookdown-BeyondMLR_files/figure-html/logitmediasex-1.png" alt="Empirical logits for the odds of trying to lose weight by TV watching and sex." width="60%" />
<p class="caption">
Figure 6.9: Empirical logits for the odds of trying to lose weight by TV watching and sex.
</p>
</div>
</div>
<div id="initial-models-2" class="section level3">
<h3><span class="header-section-number">6.7.3</span> Initial Models</h3>
<p>Our strategy for modeling is to use our questions of interest and what we have learned in the exploratory data analysis. For each model we interpret the coefficient of interest, look at the corresponding Wald test and, as a final step, compare the deviances for the different models we considered.</p>
<p>We first use a model where sex is our only predictor.</p>
<div class="sourceCode" id="cb142"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb142-1"><a href="ch-logreg.html#cb142-1"></a>model1 &lt;-<span class="st"> </span><span class="kw">glm</span>(lose.wt<span class="fl">.01</span> <span class="op">~</span><span class="st"> </span>female, <span class="dt">family =</span> binomial, </span>
<span id="cb142-2"><a href="ch-logreg.html#cb142-2"></a>              <span class="dt">data =</span> risk2009)</span></code></pre></div>
<pre><code>##             Estimate Std. Error z value  Pr(&gt;|z|)
## (Intercept)  -0.7522     0.1410  -5.334 9.588e-08
## female        1.0919     0.1978   5.520 3.382e-08</code></pre>
<pre><code>##  Residual deviance =  580.3  on  443 df</code></pre>
<p>Our estimated binomial regression model is:</p>
<p><span class="math display">\[\log\left(\frac{\hat{p}}{1-\hat{p}}\right)=-0.75+1.09 \textrm{female}\]</span>
where <span class="math inline">\(\hat{p}\)</span> is the estimated proportion of youth wanting to lose weight. We can interpret the coefficient on <code>female</code> by exponentiating <span class="math inline">\(e^{1.0919} = 2.98\)</span> (95% CI = <span class="math inline">\((2.03, 4.41)\)</span>) indicating that the odds of a female trying to lose weight is nearly three times the odds of a male trying to lose weight (<span class="math inline">\(Z=5.520\)</span>, <span class="math inline">\(p=3.38e-08\)</span>). We retain sex in the model and consider adding the BMI percentile:</p>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="ch-logreg.html#cb145-1"></a>model2 &lt;-<span class="st"> </span><span class="kw">glm</span>(lose.wt<span class="fl">.01</span> <span class="op">~</span><span class="st"> </span>female <span class="op">+</span><span class="st"> </span>bmipct, </span>
<span id="cb145-2"><a href="ch-logreg.html#cb145-2"></a>              <span class="dt">family =</span> binomial, <span class="dt">data =</span> risk2009)</span></code></pre></div>
<pre><code>##             Estimate Std. Error z value  Pr(&gt;|z|)
## (Intercept) -4.25914    0.44927  -9.480 2.541e-21
## female       1.86067    0.25896   7.185 6.714e-13
## bmipct       0.04715    0.00524   8.997 2.313e-19</code></pre>
<pre><code>##  Residual deviance =  463  on  442 df</code></pre>
<p>We see that there is statistically significant evidence (<span class="math inline">\(Z=8.997, p&lt;.001\)</span>) that BMI is positively associated with the odds of trying to lose weight, after controlling for sex. Clearly BMI percentile belongs in the model with sex.</p>
<p>Our estimated binomial regression model is:</p>
<p><span class="math display">\[\log\left(\frac{\hat{p}}{1-\hat{p}}\right)= -4.26+1.86\textrm{female}+0.047\textrm{bmipct}\]</span></p>
<p>To interpret the coefficient on <code>bmipct</code>, we will consider a 10-unit increase in <code>bmipct</code>. Because <span class="math inline">\(e^{10*0.047}=1.602\)</span>, then there is an estimated 60.2% increase in the odds of wanting to lose weight for each additional 10 percentile points of BMI for members of the same sex. Just as we had done in other multiple regression models, we need to interpret our coefficient <em>given that the other variables remain constant</em>. An interaction term for BMI by sex was tested (not shown) and it was not significant (<span class="math inline">\(Z=-0.70\)</span>, <span class="math inline">\(p=0.485\)</span>), so the effect of BMI does not differ by sex.</p>
<p>We next add <code>sport</code> to our model. Sports participation was considered for inclusion in the model in three ways: an indicator of sports participation (0 = no teams, 1 = one or more teams), treating the number of teams (0, 1, 2, or 3) as numeric, and treating the number of teams as a factor. The models below treat sports participation using an indicator variable, but all three models produced similar results.</p>
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb148-1"><a href="ch-logreg.html#cb148-1"></a>model3 &lt;-<span class="st"> </span><span class="kw">glm</span>(lose.wt<span class="fl">.01</span> <span class="op">~</span><span class="st"> </span>female <span class="op">+</span><span class="st"> </span>bmipct <span class="op">+</span><span class="st"> </span>sport, </span>
<span id="cb148-2"><a href="ch-logreg.html#cb148-2"></a>              <span class="dt">family =</span> binomial, <span class="dt">data =</span> risk2009)</span></code></pre></div>
<pre><code>##             Estimate Std. Error z value  Pr(&gt;|z|)
## (Intercept) -4.17138   0.468463 -8.9044 5.367e-19
## female       1.84951   0.259514  7.1268 1.027e-12
## bmipct       0.04728   0.005251  9.0032 2.193e-19
## sportSports -0.14767   0.235101 -0.6281 5.299e-01</code></pre>
<pre><code>##  Residual deviance =  462.6  on  441 df</code></pre>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb151-1"><a href="ch-logreg.html#cb151-1"></a>model3int &lt;-<span class="st"> </span><span class="kw">glm</span>(lose.wt<span class="fl">.01</span> <span class="op">~</span><span class="st"> </span>female <span class="op">+</span><span class="st"> </span>bmipct <span class="op">+</span><span class="st"> </span>sport <span class="op">+</span></span>
<span id="cb151-2"><a href="ch-logreg.html#cb151-2"></a><span class="st">              </span>female<span class="op">:</span>sport <span class="op">+</span><span class="st"> </span>bmipct<span class="op">:</span>sport, </span>
<span id="cb151-3"><a href="ch-logreg.html#cb151-3"></a>              <span class="dt">family =</span> binomial, <span class="dt">data =</span> risk2009)</span></code></pre></div>
<pre><code>##                     Estimate Std. Error z value
## (Intercept)        -3.643635   0.604821  -6.024
## female              1.451017   0.378547   3.833
## bmipct              0.042530   0.007211   5.898
## sportSports        -1.187199   0.893057  -1.329
## female:sportSports  0.731516   0.523566   1.397
## bmipct:sportSports  0.009908   0.010463   0.947
##                     Pr(&gt;|z|)
## (Intercept)        1.698e-09
## female             1.265e-04
## bmipct             3.684e-09
## sportSports        1.837e-01
## female:sportSports 1.624e-01
## bmipct:sportSports 3.436e-01</code></pre>
<pre><code>##  Residual deviance =  460.5  on  439 df</code></pre>
<p>Sports teams were not significant in any of these models, nor were interaction terms (sex by sports and bmipct by sports). As a result, sports participation was no longer considered for inclusion in the model.</p>
<p>We last look at adding <code>media</code> to our model.</p>
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb154-1"><a href="ch-logreg.html#cb154-1"></a>model4 &lt;-<span class="st"> </span><span class="kw">glm</span>(lose.wt<span class="fl">.01</span> <span class="op">~</span><span class="st"> </span>female <span class="op">+</span><span class="st"> </span>bmipct <span class="op">+</span><span class="st"> </span>media, </span>
<span id="cb154-2"><a href="ch-logreg.html#cb154-2"></a>              <span class="dt">family =</span> binomial, <span class="dt">data =</span> risk2009)</span></code></pre></div>
<pre><code>##             Estimate Std. Error z value  Pr(&gt;|z|)
## (Intercept) -4.08892   0.462947  -8.832 1.025e-18
## female       1.84776   0.259636   7.117 1.105e-12
## bmipct       0.04783   0.005287   9.046 1.485e-19
## media       -0.09938   0.072464  -1.371 1.702e-01</code></pre>
<pre><code>##  Residual deviance =  461.1  on  441 df</code></pre>
<p>Media is not a statistically significant term (<span class="math inline">\(Z=-1.371\)</span>, <span class="math inline">\(p=0.170\)</span>). However, because our interest centers on how media may affect attempts to lose weight and how its effect might be different for females and males, we fit a model with a media term and a sex by media interaction term (not shown). Neither term was statistically significant, so we have no support in our data that media exposure as measured by hours spent watching TV is associated with the odds a teen is trying to lose weight after accounting for sex and BMI.</p>
</div>
<div id="drop-in-deviance-tests" class="section level3">
<h3><span class="header-section-number">6.7.4</span> Drop-in-Deviance Tests</h3>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb157-1"><a href="ch-logreg.html#cb157-1"></a>drop_in_dev &lt;-<span class="st"> </span><span class="kw">anova</span>(model1, model2, model3, model4,</span>
<span id="cb157-2"><a href="ch-logreg.html#cb157-2"></a>                     <span class="dt">test=</span><span class="st">&quot;Chisq&quot;</span>)</span></code></pre></div>
<pre><code>  ResidDF ResidDev Deviance Df      pval
1     443    580.3       NA NA        NA
2     442    463.0 117.3301  1 2.431e-27
3     441    462.6   0.3947  1 5.298e-01
4     441    461.1   1.5007  0        NA</code></pre>
<pre><code>       df   AIC
model1  2 584.3
model2  3 469.0
model3  4 470.6
model4  4 469.1</code></pre>
<p>Comparing models using differences in deviances requires that the models be <strong>nested</strong>, meaning each smaller model is a simplified version of the larger model. In our case, Models 1, 2, and 4 are nested, as are Models 1, 2, and 3, but Models 3 and 4 cannot be compared using a drop-in-deviance test.</p>
<p>There is a large drop-in-deviance adding BMI to the model with sex (Model 1 to Model 2, 117.3), which is clearly statistically significant when compared to a <span class="math inline">\(\chi^2\)</span> distribution with 1 df. The drop-in-deviance for adding an indicator variable for sports to the model with sex and BMI is only 462.99 - 462.59 = 0.40. There is a difference of a single parameter, so the drop-in-deviance would be compared to a <span class="math inline">\(\chi^2\)</span> distribution with 1 df. The resulting <span class="math inline">\(p\)</span>-value is very large (.53) suggesting that adding an indicator for sports is not helpful once we’ve already accounted for BMI and sex. For comparing Models 3 and 4, one approach is to look at the AIC. In this case, the AIC is (barely) smaller for the model with media, providing evidence that the latter model is slightly preferable.</p>
</div>
<div id="model-discussion-and-summary" class="section level3">
<h3><span class="header-section-number">6.7.5</span> Model Discussion and Summary</h3>
<p>We found that the odds of wanting to lose weight are considerably greater for females compared to males. In addition, respondents with greater BMI percentiles express a greater desire to lose weight for members of the same sex. Regardless of sex or BMI percentile, sports participation and TV watching are not associated with different odds for wanting to lose weight.</p>
<p>A limitation of this analysis is that we used complete cases in place of a method of imputing responses or modeling missingness. This reduced our sample from 500 to 445, and it may have introduced bias. For example, if respondents who watch a lot of TV were unwilling to reveal as much, and if they differed with respect to their desire to lose weight from those respondents who reported watching little TV, our inferences regarding the relationship between lots of TV and desire to lose weight may be biased.</p>
<p>Other limitations may result from definitions. Trying to lose weight is self-reported and may not correlate with any action undertaken to do so. The number of sports teams may not accurately reflect sports-related pressures to lose weight. For example, elite athletes may focus on a single sport and be subject to greater pressures, whereas athletes who casually participate in three sports may not feel any pressure to lose weight. Hours spent watching TV are not likely to encompass the totality of media exposure, particularly because exposure to celebrities occurs often online. Furthermore, this analysis does not explore in any detail maladaptions—inappropriate motivations for wanting to lose weight. For example, we did not focus our study on subsets of respondents with low BMI who are attempting to lose weight.</p>
<p>It would be instructive to use data science methodologies to explore the entire data set of 16,000 instead of sampling 500. However, the types of exploration and models used here could translate to the larger sample size.</p>
<p>Finally a limitation may be introduced as a result of the acknowledged variation in the administration of the YRBSS. States and local authorities are allowed to administer the survey as they see fit, which at times results in significant variation in sample selection and response.</p>
</div>
</div>
<div id="exercises-5" class="section level2">
<h2><span class="header-section-number">6.8</span> Exercises</h2>
<div id="conceptual-exercises-3" class="section level3">
<h3><span class="header-section-number">6.8.1</span> Conceptual Exercises</h3>
<ol style="list-style-type: decimal">
<li><p>List the explanatory and response variable(s) for each research question.</p>
<ol style="list-style-type: lower-alpha">
<li>Are students with poor grades more likely to binge drink?</li>
<li>What is the chance you are accepted into medical school given your GPA and MCAT scores?</li>
<li>Is a single mom more likely to marry the baby’s father if she has a boy?</li>
<li>Are students participating in sports in college more or less likely to graduate?</li>
<li>Is exposure to a particular chemical associated with a cancer diagnosis?</li>
</ol></li>
<li><p>Interpret the odds ratios in the following abstract.</p>
<p><em>Daycare Centers and Respiratory Health</em> <span class="citation">(Nafstad et al. <a href="#ref-Nafstad1999" role="doc-biblioref">1999</a>)</span></p>
<ul>
<li><p><strong>Objective</strong>. To estimate the effects of the type of daycare on respiratory health in preschool children.</p></li>
<li><p><strong>Methods</strong>. A population-based, cross-sectional study of Oslo children born in 1992 was conducted at the end of 1996. A self-administered questionnaire inquired about daycare arrangements, environmental conditions, and family characteristics (n = 3853; response rate, 79%).</p></li>
<li><p><strong>Results</strong>. In a logistic regression controlling for confounding, children in daycare centers had more often nightly cough (adjusted odds ratio, 1.89; 95% confidence interval 1.34-2.67), and blocked or runny nose without common cold (1.55; 1.07-1.61) during the past 12 months compared with children in home care.</p></li>
</ul></li>
<li><p>Construct a table and calculate the corresponding odds and odds ratios. Comment on the reported and calculated results in this <em>New York Times</em> article from <span class="citation">Kolata (<a href="#ref-Kolata2009" role="doc-biblioref">2009</a>)</span>.</p>
<ul>
<li><p>In November, the Centers for Disease Control and Prevention published a paper reporting that babies conceived with IVF, or with a technique in which sperm are injected directly into eggs, have a slightly increased risk of several birth defects, including a hole between the two chambers of the heart, a cleft lip or palate, an improperly developed esophagus and a malformed rectum. The study involved 9,584 babies with birth defects and 4,792 babies without. Among the mothers of babies without birth defects, 1.1% had used IVF or related methods, compared with 2.4% of mothers of babies with birth defects.</p></li>
<li><p>The findings are considered preliminary, and researchers say they believe IVF does not carry excessive risks. There is a 3% chance that any given baby will have a birth defect.</p></li>
</ul></li>
<li><p>In a small pilot study, researchers compared two groups of 3 turbine wheels each under low humidity and two groups of 3 turbine wheels each under high-humidity conditions to determine if humidity is related to the number of fissures that occur. If <span class="math inline">\(Y\)</span> = number of turbine wheels that develop fissures, then assume that <span class="math inline">\(Y \sim \textrm{Binomial}(n=3, p=p_L)\)</span> under low humidity, and <span class="math inline">\(Y \sim \textrm{Binomial}(n=3, p=p_H)\)</span> under high humidity, where <span class="math inline">\(f(y;p)=\binom{n}{y} p^y (1-p)^{n-y}\)</span>. Write out the log-likelihood function <span class="math inline">\(\textrm{logL}(p_L, p_H)\)</span>, using the data in Table <a href="ch-logreg.html#tab:fissurechp6">6.4</a> and simplifying where possible.</p></li>
</ol>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:fissurechp6">Table 6.4: </span>Data for Conceptual Exercise 4.
</caption>
<thead>
<tr>
<th style="text-align:left;">
Turbine group
</th>
<th style="text-align:left;">
1
</th>
<th style="text-align:left;">
2
</th>
<th style="text-align:left;">
3
</th>
<th style="text-align:left;">
4
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;width: 5cm; ">
Humidity
</td>
<td style="text-align:left;">
Low
</td>
<td style="text-align:left;">
Low
</td>
<td style="text-align:left;">
High
</td>
<td style="text-align:left;">
High
</td>
</tr>
<tr>
<td style="text-align:left;width: 5cm; ">
n = number of turbine wheels
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:left;">
3
</td>
</tr>
<tr>
<td style="text-align:left;width: 5cm; ">
y = number of fissures
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
2
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
0
</td>
</tr>
</tbody>
</table>
</div>
<div id="guided-exercises-4" class="section level3">
<h3><span class="header-section-number">6.8.2</span> Guided Exercises</h3>
<ol style="list-style-type: decimal">
<li><p><strong>Soccer goals on target.</strong> Data comes from an article in <em>Psychological Science</em> <span class="citation">(Roskes et al. <a href="#ref-Roskes2011" role="doc-biblioref">2011</a>)</span>. The authors report on the success rate of penalty kicks that were on-target, so that either the keeper saved the shot or the shot scored, for FIFA World Cup shootouts between 1982 and 2010. They found that 18 out of 20 shots were scored when the goalkeeper’s team was behind, 71 out of 90 shots were scored when the game was tied, and 55 out of 75 shots were scored with the goalkeeper’s team ahead.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Calculate the odds of a successful penalty kick for games in which the goalkeeper’s team was behind, tied, or ahead. Then, construct empirical odds ratios for successful penalty kicks for (a) behind versus tied, and (b) tied versus ahead.</p></li>
<li><p>Fit a model with the categorical predictor c(“behind”,“tied”,“ahead”) and interpret the exponentiated coefficients. How do they compare to the empirical odds ratios you calculated?</p></li>
</ol></li>
<li><p><strong>Medical school admissions.</strong> The data for Medical School Admissions is in <code>MedGPA.csv</code>, taken from undergraduates from a small liberal arts school over several years. We are interested in student attributes that are associated with higher acceptance rates.</p>
<ul>
<li><code>Accept</code> = accepted (A) into medical school or denied (D)</li>
<li><code>Acceptance</code> = accepted (1) into medical school or denied (0)</li>
<li><code>Sex</code> = male (M) or female (F)</li>
<li><code>BCPM</code> = GPA in natural sciences and mathematics</li>
<li><code>GPA</code> = overall GPA</li>
<li><code>VR</code> = verbal reasoning subscale score of the MCAT</li>
<li><code>PS</code> = physical sciences subscale score of the MCAT</li>
<li><code>WS</code> = writing samples subscale score of the MCAT</li>
<li><code>BS</code> = biological sciences subscale score of the MCAT</li>
<li><code>MCAT</code> = MCAT total score</li>
<li><code>Apps</code> = number of schools applied to</li>
</ul>
<p>Be sure to interpret model coefficients and associated tests of significance or confidence intervals when answering the following questions:</p>
<ol style="list-style-type: lower-alpha">
<li>Compare the relative effects of improving your MCAT score versus improving your GPA on your odds of being accepted to medical school.</li>
<li>After controlling for MCAT and GPA, is the number of applications related to odds of getting into medical school?</li>
<li>Is one MCAT subscale more important than the others?</li>
<li>Is there any evidence that the effect of MCAT score or GPA differs for males and females?</li>
</ol></li>
<li><p><strong>Moths.</strong> An article in the <em>Journal of Animal Ecology</em> by <span class="citation">Bishop (<a href="#ref-Bishop1972" role="doc-biblioref">1972</a>)</span> investigated whether moths provide evidence of “survival of the fittest” with their camouflage traits. Researchers glued equal numbers of light and dark morph moths in lifelike positions on tree trunks at 7 locations from 0 to 51.2 km from Liverpool. They then recorded the number of moths removed after 24 hours, presumably by predators. The hypothesis was that, since tree trunks near Liverpool were blackened by pollution, light morph moths would be more likely to be removed near Liverpool.</p>
<p>Data <span class="citation">(Ramsey and Schafer <a href="#ref-Ramsey2002" role="doc-biblioref">2002</a>)</span> can be found in <code>moth.csv</code> and contains the variables below. In addition, R code at the end of the problem can be used to input the data and create additional useful variables.</p>
<ul>
<li><code>MORPH</code> = light or dark</li>
<li><code>DISTANCE</code> = kilometers from Liverpool</li>
<li><code>PLACED</code> = number of moths of a specific morph glued to trees at that location</li>
<li><code>REMOVED</code> = number of moths of a specific morph removed after 24 hours</li>
</ul>
<ol style="list-style-type: lower-alpha">
<li>What are logits in this study?</li>
<li>Create an empirical logit plot of logits vs. distance by morph. What can we conclude from this plot?</li>
<li>Create a model with <code>DISTANCE</code> and <code>dark</code>. Interpret all the coefficients.</li>
<li>Create a model with <code>DISTANCE</code>, <code>dark</code>, and the interaction between both variables. Interpret all the coefficients.</li>
<li>Interpret a drop-in-deviance test and a Wald test to test the significance of the interaction term in (d).</li>
<li>Test the goodness-of-fit for the interaction model. What can we conclude about this model?</li>
<li>Is there evidence of overdispersion in the interaction model? What factors might lead to overdispersion in this case? Regardless of your answer, repeat (d) adjusting for overdispersion.</li>
<li>Compare confidence intervals for coefficients in your models from (g) and (d).</li>
<li>What happens if we expand the data set to contain one row per moth (968 rows)? Now we can run a logistic binary regression model. How does the logistic binary regression model compare to the binomial regression model? What are similarities and differences? Would there be any reason to run a logistic binomial regression rather than a logistic binary regression in a case like this? Some starter code can be found below the input code.</li>
</ol></li>
</ol>
<div class="sourceCode" id="cb160"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb160-1"><a href="ch-logreg.html#cb160-1"></a>moth &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;data/moth.csv&quot;</span>)</span>
<span id="cb160-2"><a href="ch-logreg.html#cb160-2"></a>moth &lt;-<span class="st"> </span><span class="kw">mutate</span>(moth, </span>
<span id="cb160-3"><a href="ch-logreg.html#cb160-3"></a>               <span class="dt">notremoved =</span> PLACED <span class="op">-</span><span class="st"> </span>REMOVED, </span>
<span id="cb160-4"><a href="ch-logreg.html#cb160-4"></a>               <span class="dt">logit1 =</span> <span class="kw">log</span>(REMOVED <span class="op">/</span><span class="st"> </span>notremoved),</span>
<span id="cb160-5"><a href="ch-logreg.html#cb160-5"></a>               <span class="dt">prop1 =</span> REMOVED <span class="op">/</span><span class="st"> </span>PLACED, </span>
<span id="cb160-6"><a href="ch-logreg.html#cb160-6"></a>               <span class="dt">dark =</span> <span class="kw">ifelse</span>(MORPH<span class="op">==</span><span class="st">&quot;dark&quot;</span>,<span class="dv">1</span>,<span class="dv">0</span>) )</span></code></pre></div>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb161-1"><a href="ch-logreg.html#cb161-1"></a>mtemp1 =<span class="st"> </span><span class="kw">rep</span>(moth<span class="op">$</span>dark[<span class="dv">1</span>],moth<span class="op">$</span>REMOVED[<span class="dv">1</span>])</span>
<span id="cb161-2"><a href="ch-logreg.html#cb161-2"></a>dtemp1 =<span class="st"> </span><span class="kw">rep</span>(moth<span class="op">$</span>DISTANCE[<span class="dv">1</span>],moth<span class="op">$</span>REMOVED[<span class="dv">1</span>])</span>
<span id="cb161-3"><a href="ch-logreg.html#cb161-3"></a>rtemp1 =<span class="st"> </span><span class="kw">rep</span>(<span class="dv">1</span>,moth<span class="op">$</span>REMOVED[<span class="dv">1</span>])</span>
<span id="cb161-4"><a href="ch-logreg.html#cb161-4"></a>mtemp1 =<span class="st"> </span><span class="kw">c</span>(mtemp1,<span class="kw">rep</span>(moth<span class="op">$</span>dark[<span class="dv">1</span>],</span>
<span id="cb161-5"><a href="ch-logreg.html#cb161-5"></a>                      moth<span class="op">$</span>PLACED[<span class="dv">1</span>]<span class="op">-</span>moth<span class="op">$</span>REMOVED[<span class="dv">1</span>]))</span>
<span id="cb161-6"><a href="ch-logreg.html#cb161-6"></a>dtemp1 =<span class="st"> </span><span class="kw">c</span>(dtemp1,<span class="kw">rep</span>(moth<span class="op">$</span>DISTANCE[<span class="dv">1</span>],</span>
<span id="cb161-7"><a href="ch-logreg.html#cb161-7"></a>                      moth<span class="op">$</span>PLACED[<span class="dv">1</span>]<span class="op">-</span>moth<span class="op">$</span>REMOVED[<span class="dv">1</span>]))</span>
<span id="cb161-8"><a href="ch-logreg.html#cb161-8"></a>rtemp1 =<span class="st"> </span><span class="kw">c</span>(rtemp1,<span class="kw">rep</span>(<span class="dv">0</span>,moth<span class="op">$</span>PLACED[<span class="dv">1</span>]<span class="op">-</span>moth<span class="op">$</span>REMOVED[<span class="dv">1</span>]))</span>
<span id="cb161-9"><a href="ch-logreg.html#cb161-9"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">2</span><span class="op">:</span><span class="dv">14</span>)  {</span>
<span id="cb161-10"><a href="ch-logreg.html#cb161-10"></a>  mtemp1 =<span class="st"> </span><span class="kw">c</span>(mtemp1,<span class="kw">rep</span>(moth<span class="op">$</span>dark[i],moth<span class="op">$</span>REMOVED[i]))</span>
<span id="cb161-11"><a href="ch-logreg.html#cb161-11"></a>  dtemp1 =<span class="st"> </span><span class="kw">c</span>(dtemp1,<span class="kw">rep</span>(moth<span class="op">$</span>DISTANCE[i],moth<span class="op">$</span>REMOVED[i]))</span>
<span id="cb161-12"><a href="ch-logreg.html#cb161-12"></a>  rtemp1 =<span class="st"> </span><span class="kw">c</span>(rtemp1,<span class="kw">rep</span>(<span class="dv">1</span>,moth<span class="op">$</span>REMOVED[i]))</span>
<span id="cb161-13"><a href="ch-logreg.html#cb161-13"></a>  mtemp1 =<span class="st"> </span><span class="kw">c</span>(mtemp1,<span class="kw">rep</span>(moth<span class="op">$</span>dark[i],</span>
<span id="cb161-14"><a href="ch-logreg.html#cb161-14"></a>                        moth<span class="op">$</span>PLACED[i]<span class="op">-</span>moth<span class="op">$</span>REMOVED[i]))</span>
<span id="cb161-15"><a href="ch-logreg.html#cb161-15"></a>  dtemp1 =<span class="st"> </span><span class="kw">c</span>(dtemp1,<span class="kw">rep</span>(moth<span class="op">$</span>DISTANCE[i],</span>
<span id="cb161-16"><a href="ch-logreg.html#cb161-16"></a>                        moth<span class="op">$</span>PLACED[i]<span class="op">-</span>moth<span class="op">$</span>REMOVED[i]))</span>
<span id="cb161-17"><a href="ch-logreg.html#cb161-17"></a>  rtemp1 =<span class="st"> </span><span class="kw">c</span>(rtemp1,<span class="kw">rep</span>(<span class="dv">0</span>,moth<span class="op">$</span>PLACED[i]<span class="op">-</span>moth<span class="op">$</span>REMOVED[i]))  }</span>
<span id="cb161-18"><a href="ch-logreg.html#cb161-18"></a>newdata =<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">removed=</span>rtemp1,<span class="dt">dark=</span>mtemp1,<span class="dt">dist=</span>dtemp1)</span>
<span id="cb161-19"><a href="ch-logreg.html#cb161-19"></a>newdata[<span class="dv">1</span><span class="op">:</span><span class="dv">25</span>,]</span>
<span id="cb161-20"><a href="ch-logreg.html#cb161-20"></a><span class="kw">cdplot</span>(<span class="kw">as.factor</span>(rtemp1)<span class="op">~</span>dtemp1)</span></code></pre></div>
<ol start="4" style="list-style-type: decimal">
<li><p><strong>Birdkeeping and lung cancer: a retrospective observational study.</strong> A 1972-1981 health survey in The Hague, Netherlands, discovered an association between keeping pet birds and increased risk of lung cancer. To investigate birdkeeping as a risk factor, researchers conducted a case-control study of patients in 1985 at four hospitals in The Hague. They identified 49 cases of lung cancer among patients who were registered with a general practice, who were age 65 or younger, and who had resided in the city since 1965. Each patient (case) with cancer was matched with two control subjects (without cancer) by age and sex. Further details can be found in <span class="citation">Holst, Kromhout, and Brand (<a href="#ref-Holst1988" role="doc-biblioref">1988</a>)</span>.</p>
<p>Age, sex, and smoking history are all known to be associated with lung cancer incidence. Thus, researchers wished to determine after age, sex, socioeconomic status, and smoking have been controlled for, is an additional risk associated with birdkeeping? The data <span class="citation">(Ramsey and Schafer <a href="#ref-Ramsey2002" role="doc-biblioref">2002</a>)</span> is found in <code>birdkeeping.csv</code>, and the variables are listed below. In addition, R code at the end of the problem can be used to input the data and create additional useful variables.</p>
<ul>
<li><code>female</code> = sex (1 = Female, 0 = Male)</li>
<li><code>age</code> = age, in years</li>
<li><code>highstatus</code> = socioeconomic status (1 = High, 0 = Low), determined by the occupation of the household’s primary wage earner</li>
<li><code>yrsmoke</code> = years of smoking prior to diagnosis or examination</li>
<li><code>cigsday</code> = average rate of smoking, in cigarettes per day</li>
<li><code>bird</code> = indicator of birdkeeping (1 = Yes, 0 = No), determined by whether or not there were caged birds in the home for more than 6 consecutive months from 5 to 14 years before diagnosis (cases) or examination (controls)</li>
<li><code>cancer</code> = indicator of lung cancer diagnosis (1 = Cancer, 0 = No Cancer)</li>
</ul>
<ol style="list-style-type: lower-alpha">
<li>Perform an exploratory data analysis to see how each explanatory variable is related to the response (<code>cancer</code>). Summarize each relationship in one sentence.</li>
</ol>
<ul>
<li><p>For quantitative explanatory variables (<code>age</code>, <code>yrsmoke</code>, <code>cigsday</code>), produce a cdplot, a boxplot, and summary statistics by cancer diagnosis.</p></li>
<li><p>For categorical explanatory variables (<code>female</code> or <code>sex</code>, <code>highstatus</code> or <code>socioecon_status</code>, <code>bird</code> or <code>keep_bird</code>), produce a segmented bar chart and an appropriate table of proportions showing the relationship with cancer diagnosis.</p></li>
</ul>
<ol start="2" style="list-style-type: lower-alpha">
<li><p>In (a), you should have found no relationship between whether or not a patient develops lung cancer and either their age or sex. Why might this be? What implications will this have on your modeling?</p></li>
<li><p>Based on a two-way table with keeping birds and developing lung cancer from (a), find an unadjusted odds ratio comparing birdkeepers to non-birdkeepers and interpret this odds ratio in context. (Note: an <em>unadjusted</em> odds ratio is found by <em>not</em> controlling for any other variables.) Also, find an analogous relative risk and interpret it in context as well.</p></li>
<li><p>Are the elogits reasonably linear relating number of years smoked to the estimated log odds of developing lung cancer? Demonstrate with an appropriate plot.</p></li>
<li><p>Does there appear to be an interaction between number of years smoked and whether the subject keeps a bird? Demonstrate with an interaction plot and a coded scatterplot with empirical logits on the y-axis.</p></li>
</ol>
<p>Before answering the next questions, fit logistic regression models in R with <code>cancer</code> as the response and the following sets of explanatory variables:</p>
<ul>
<li><code>model1</code> = <code>age</code>, <code>yrsmoke</code>, <code>cigsday</code>, <code>female</code>, <code>highstatus</code>, <code>bird</code></li>
<li><code>model2</code> = <code>yrsmoke</code>, <code>cigsday</code>, <code>highstatus</code>, <code>bird</code></li>
<li><code>model4</code> = <code>yrsmoke</code>, <code>bird</code></li>
<li><code>model5</code> = the complete second order version of <code>model4</code> (add squared terms and an interaction)</li>
<li><code>model6</code> = <code>yrsmoke</code>, <code>bird</code>, <code>yrsmoke:bird</code></li>
</ul>
<ol start="6" style="list-style-type: lower-alpha">
<li><p>Is there evidence that we can remove <code>age</code> and <code>female</code> from our model? Perform an appropriate test comparing <code>model1</code> to <code>model2</code>; give a test statistic and p-value, and state a conclusion in context.</p></li>
<li><p>Is there evidence that the complete second order version of <code>model4</code> improves its performance? Perform an appropriate test comparing <code>model4</code> to <code>model5</code>; give a test statistic and p-value, and state a conclusion in context.</p></li>
<li><p>Carefully interpret each of the four model coefficients in <code>model6</code> in context.</p></li>
<li><p>If you replaced <code>yrsmoke</code> everywhere it appears in <code>model6</code> with a mean-centered version of <code>yrsmoke</code>, tell what would change among these elements: the 4 coefficients, the 4 p-values for coefficients, and the residual deviance.</p></li>
<li><p><code>model4</code> is a potential final model based on this set of explanatory variables. Find and carefully interpret 95% confidence intervals based on profile likelihoods for the coefficients of <code>yrsmoke</code> and <code>bird</code>.</p></li>
<li><p>How does the adjusted odds ratio for birdkeeping from <code>model4</code> compare with the unadjusted odds ratio you found in (c)? Is birdkeeping associated with a significant increase in the odds of developing lung cancer, even after adjusting for other factors?</p></li>
<li><p>Use the categorical variable <code>years_factor</code> based on <code>yrsmoke</code> and replace <code>yrsmoke</code> in <code>model4</code> with your new variable to create <code>model4a</code>. First, interpret the coefficient for <code>years_factorOver 25 years</code> in context. Then tell if you prefer <code>model4</code> with years smoked as a numeric predictor or <code>model4a</code> with years smoked as a categorical predictor, and explain your reasoning.</p></li>
<li><p>Discuss the scope of inference in this study. Can we generalize our findings beyond the subjects in this study? Can we conclude that birdkeeping causes increased odds of developing lung cancer? Do you have other concerns with this study design or the analysis you carried out?</p></li>
<li><p>Read the article that appeared in the <em>British Medical Journal</em>. What similarities and differences do you see between their analyses and yours? What are a couple of things you learned from the article that weren’t apparent in the short summary at the beginning of the assignment.</p></li>
</ol></li>
</ol>
<div class="sourceCode" id="cb162"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb162-1"><a href="ch-logreg.html#cb162-1"></a>birds &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;data/birdkeeping.csv&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb162-2"><a href="ch-logreg.html#cb162-2"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">sex =</span> <span class="kw">ifelse</span>(female <span class="op">==</span><span class="st"> </span><span class="dv">1</span>, <span class="st">&quot;Female&quot;</span>, <span class="st">&quot;Male&quot;</span>),</span>
<span id="cb162-3"><a href="ch-logreg.html#cb162-3"></a>         <span class="dt">socioecon_status =</span> <span class="kw">ifelse</span>(highstatus <span class="op">==</span><span class="st"> </span><span class="dv">1</span>, </span>
<span id="cb162-4"><a href="ch-logreg.html#cb162-4"></a>                                   <span class="st">&quot;High&quot;</span>, <span class="st">&quot;Low&quot;</span>),</span>
<span id="cb162-5"><a href="ch-logreg.html#cb162-5"></a>         <span class="dt">keep_bird =</span> <span class="kw">ifelse</span>(bird <span class="op">==</span><span class="st"> </span><span class="dv">1</span>, <span class="st">&quot;Keep Bird&quot;</span>, <span class="st">&quot;No Bird&quot;</span>),</span>
<span id="cb162-6"><a href="ch-logreg.html#cb162-6"></a>         <span class="dt">lung_cancer =</span> <span class="kw">ifelse</span>(cancer <span class="op">==</span><span class="st"> </span><span class="dv">1</span>, <span class="st">&quot;Cancer&quot;</span>, </span>
<span id="cb162-7"><a href="ch-logreg.html#cb162-7"></a>                              <span class="st">&quot;No Cancer&quot;</span>)) <span class="op">%&gt;%</span></span>
<span id="cb162-8"><a href="ch-logreg.html#cb162-8"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">years_factor =</span> <span class="kw">cut</span>(yrsmoke, </span>
<span id="cb162-9"><a href="ch-logreg.html#cb162-9"></a>                            <span class="dt">breaks =</span> <span class="kw">c</span>(<span class="op">-</span><span class="ot">Inf</span>, <span class="dv">0</span>, <span class="dv">25</span>, <span class="ot">Inf</span>),</span>
<span id="cb162-10"><a href="ch-logreg.html#cb162-10"></a>            <span class="dt">labels =</span> <span class="kw">c</span>(<span class="st">&quot;No smoking&quot;</span>, <span class="st">&quot;1-25 years&quot;</span>, </span>
<span id="cb162-11"><a href="ch-logreg.html#cb162-11"></a>                       <span class="st">&quot;Over 25 years&quot;</span>)))</span></code></pre></div>
<ol start="5" style="list-style-type: decimal">
<li><p><strong>2016 Election.</strong> An <a href="https://www.causeweb.org/usproc/usclap/2018/spring/winners">award-winning</a> student project <span class="citation">(Blakeman, Renier, and Shandaq <a href="#ref-Renier2018" role="doc-biblioref">2018</a>)</span> examined driving forces behind Donald Trump’s surprising victory in the 2016 Presidential Election, using data from nearly 40,000 voters collected as part of the 2016 Cooperative Congressional Election Survey (CCES). The student researchers investigated two theories: (1) Trump was seen as the candidate of change for voters experiencing economic hardship, and (2) Trump exploited voter fears about immigrants and minorities.</p>
<p>The data set <code>electiondata.csv</code> has individual level data on voters in the 2016 Presidential Election, collected from the CCES and subsequently tidied. We will focus on the following variables:</p>
<ul>
<li><code>Vote</code> = 1 if Trump; 0 if another candidate</li>
<li><code>zfaminc</code> = family income expressed as a z-score (number of standard deviations above or below the mean)</li>
<li><code>zmedinc</code> = state median income expressed as a z-score</li>
<li><code>EconWorse</code> = 1 if the voter believed the economy had gotten worse in the past 4 years; 0 otherwise</li>
<li><code>EducStatus</code> = 1 if the voter had at least a bachelor’s degree; 0 otherwise</li>
<li><code>republican</code> = 1 if the voter identified as Republican; 0 otherwise</li>
<li><code>Noimmigrants</code> = 1 if the voter supported at least 1 of 2 anti-immigrant policy statements; 0 if neither</li>
<li><code>propforeign</code> = proportion foreign born in the state</li>
<li><code>evangelical</code> = 1 if <code>pew_bornagain</code> is 2; otherwise 0</li>
</ul>
<p>The questions below address Theory 1 (Economic Model). We want to see if there is significant evidence that voting for Trump was associated with family income level and/or with a belief that the economy became worse during the Obama Administration.</p>
<ol style="list-style-type: lower-alpha">
<li>Create a plot showing the relationship between whether voters voted for Trump and their opinion about the status of the economy. What do you find?</li>
<li>Repeat (a) separately for Republicans and non-Republicans. Again describe what you find.</li>
<li>Create a plot with one observation per state showing the relationship between a state’s median income and the log odds of a resident of that state voting for Trump. What can you conclude from this plot?</li>
</ol>
<p>Answer (d)-(f) based on <code>model1a</code> below:</p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Interpret the coefficient for <code>zmedinc</code> in context.</li>
<li>Interpret the coefficient for <code>republican</code> in context.</li>
<li>Interpret the coefficient for <code>EconWorse:republican</code> in context. What does this allow us to conclude about Theory 1?<br />
</li>
<li>Repeat the above process for Theory 2 (Immigration Model). That is, produce meaningful exploratory plots, fit a model to the data with special emphasis on <code>Noimmigrants</code>, interpret meaningful coefficients, and state what can be concluded about Theory 2.</li>
<li>Is there any concern about the independence assumption in these models? We will return to this question in later chapters.</li>
</ol></li>
</ol>
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb163-1"><a href="ch-logreg.html#cb163-1"></a>model1a &lt;-<span class="st"> </span><span class="kw">glm</span>(Vote01 <span class="op">~</span><span class="st"> </span>zfaminc <span class="op">+</span><span class="st"> </span>zmedinc <span class="op">+</span><span class="st"> </span>EconWorse <span class="op">+</span></span>
<span id="cb163-2"><a href="ch-logreg.html#cb163-2"></a><span class="st">    </span>EducStatus <span class="op">+</span><span class="st"> </span>republican <span class="op">+</span><span class="st"> </span>EducStatus<span class="op">:</span>republican <span class="op">+</span></span>
<span id="cb163-3"><a href="ch-logreg.html#cb163-3"></a><span class="st">    </span>EconWorse<span class="op">:</span>zfaminc <span class="op">+</span><span class="st"> </span>EconWorse<span class="op">:</span>republican, </span>
<span id="cb163-4"><a href="ch-logreg.html#cb163-4"></a>    <span class="dt">family =</span> binomial, <span class="dt">data =</span> electiondata)</span>
<span id="cb163-5"><a href="ch-logreg.html#cb163-5"></a><span class="kw">summary</span>(model1a)</span></code></pre></div>
</div>
<div id="open-ended-exercises-3" class="section level3">
<h3><span class="header-section-number">6.8.3</span> Open-Ended Exercises</h3>
<ol style="list-style-type: decimal">
<li><p><strong>2008 Presidential voting in Minnesota counties.</strong> Data in <code>mn08.csv</code> contains results from the 2008 U.S. Presidential Election by county in Minnesota, focusing on the two primary candidates (Democrat Barack Obama and Republican John McCain). You can consider the response to be either the percent of Obama votes in a county (binomial) or whether or not Obama had more votes than McCain (binary). Then build a model for your response using county-level predictors listed below. Interpret the results of your model.</p>
<ul>
<li><code>County</code> = county name</li>
<li><code>Obama</code> = total votes for Obama</li>
<li><code>McCain</code> = total votes for McCain</li>
<li><code>pct_Obama</code> = percent of votes for Obama</li>
<li><code>pct_rural</code> = percent of county who live in a rural setting</li>
<li><code>medHHinc</code> = median household income</li>
<li><code>unemp_rate</code> = unemployment rate</li>
<li><code>pct_poverty</code> = percent living below the poverty line</li>
<li><code>medAge2007</code> = median age in 2007</li>
<li><code>medAge2000</code> = median age in 2000</li>
<li><code>Gini_Index</code> = measure of income disparity in a county</li>
<li><code>pct_native</code> = percent of native born residents</li>
</ul></li>
<li><p><strong>Crime on campus.</strong> The data set <code>c_data2.csv</code> contains statistics on violent crimes and property crimes for a sample of 81 U.S. colleges and universities. Characterize rates of violent crimes as a proportion of total crimes reported (i.e., <code>num_viol</code> / <code>total_crime</code>). Do they differ based on type of institution, size of institution, or region of the country?</p>
<ul>
<li><code>Enrollment</code> = number of students enrolled</li>
<li><code>type</code> = university (U) or college (C)</li>
<li><code>num_viol</code> = number of violent crimes reported</li>
<li><code>num_prop</code> = number of property crimes reported</li>
<li><code>viol_rate_10000</code> = violent crime rate per 10,000 students enrolled</li>
<li><code>prop_rate_10000</code> = property crime rate per 10,000 students enrolled</li>
<li><code>total_crime</code> = total crimes reported (property and violent)</li>
<li><code>region</code> = region of the country</li>
</ul></li>
<li><p><strong>NBA data.</strong> Data in <code>NBA1718team.csv</code> <span class="citation">(Kaggle <a href="#ref-rossotti" role="doc-biblioref">2018</a><a href="#ref-rossotti" role="doc-biblioref">b</a>)</span> looks at factors that are associated with a professional basketball team’s winning percentage in the 2017-18 season. After thorough exploratory data analyses, create the best model you can to predict a team’s winning percentage; be careful of collinearity between the covariates. Based on your EDA and modeling, describe the factors that seem to explain a team’s success.</p>
<ul>
<li><code>win_pct</code> = Percentage of Wins,</li>
<li><code>FT_pct</code> = Average Free Throw Percentage per game,</li>
<li><code>TOV</code> = Average Turnovers per game,</li>
<li><code>FGA</code> = Average Field Goal Attempts per game,</li>
<li><code>FG</code> = Average Field Goals Made per game,</li>
<li><code>attempts_3P</code> = Average 3 Point Attempts per game,</li>
<li><code>avg_3P_pct</code> = Average 3 Point Percentage per game,</li>
<li><code>PTS</code> = Average Points per game,</li>
<li><code>OREB</code> = Average Offensive Rebounds per game,</li>
<li><code>DREB</code> = Average Defensive Rebounds per game,</li>
<li><code>REB</code> = Average Total Rebounds per game,</li>
<li><code>AST</code> = Average Assists per game,</li>
<li><code>STL</code> = Average Steals per game,</li>
<li><code>BLK</code> = Average Blocks per game,</li>
<li><code>PF</code> = Average Fouls per game,</li>
<li><code>attempts_2P</code> = Average 2 Point Attempts per game</li>
</ul></li>
<li><p><strong>Trashball.</strong> Great for a rainy day! A fun way to generate overdispersed binomial data. Each student crumbles an 8.5 by 11 inch sheet and tosses it from three prescribed distances ten times each. The response is the number of made baskets out of 10 tosses, keeping track of the distance. Have the class generate and collect potential covariates, and include them in your data set (e.g., years of basketball experience, using a tennis ball instead of a sheet of paper, height). Some sample analysis steps:</p>
<ol style="list-style-type: lower-alpha">
<li>Create scatterplots of logits vs. continuous predictors (distance, height, shot number, etc.) and boxplots of logit vs. categorical variables (sex, type of ball, etc.). Summarize important trends in one or two sentences.</li>
<li>Create a graph with empirical logits vs. distance plotted separately by type of ball. What might you conclude from this plot?</li>
<li>Find a binomial model using the variables that you collected. Give a brief discussion on your findings.</li>
</ol></li>
</ol>

</div>
</div>
</div>
<h3>References</h3>
<div id="refs" class="references">
<div id="ref-Bayer2011">
<p>Bayer, Ben, and Michael Fitzgerald. 2011. “Reconstructing Alabama: Reconstruction Era Demographic and Statistical Research.”</p>
</div>
<div id="ref-Bishop1972">
<p>Bishop, J. A. 1972. “An Experimental Study of the Cline of Industrial Melanism in Biston Betularia (L.) (Lepidoptera) Between Urban Liverpool and Rural North Wales.” <em>Journal of Animal Ecology</em> 41 (1): 209–43. <a href="https://doi.org/10.2307/3513">https://doi.org/10.2307/3513</a>.</p>
</div>
<div id="ref-Renier2018">
<p>Blakeman, Margaret, Tim Renier, and Rami Shandaq. 2018. “Modeling Donald Trump’s Voters in the 2016 Election.”</p>
</div>
<div id="ref-YRBS2009">
<p>Centers for Disease Control and Prevention. 2009. “Youth Risk Behavior Survey Data.” <a href="http://www.cdc.gov/HealthyYouth/yrbs/index.htm">http://www.cdc.gov/HealthyYouth/yrbs/index.htm</a>.</p>
</div>
<div id="ref-Grabe2008">
<p>Grabe, Shelly, Janet Shibley Hyde, and L. Moniquee Ward. 2008. “The Role of the Media in Body Image Concerns Among Women: A Meta-Analysis of Experimental and Correlational Studies.” <em>Pyschological Bulletin</em> 134 (3): 460–76. <a href="https://doi.org/10.1037/0033-2909.134.3.460">https://doi.org/10.1037/0033-2909.134.3.460</a>.</p>
</div>
<div id="ref-Holst1988">
<p>Holst, P. A., D. Kromhout, and R. Brand. 1988. “For Debate: Pet Birds as an Independent Risk Factor for Lung Cancer.” <em>British Medical Journal</em> 297 (6659): 1319–21. <a href="https://doi.org/10.1136/bmj.297.6659.1319">https://doi.org/10.1136/bmj.297.6659.1319</a>.</p>
</div>
<div id="ref-rossotti">
<p>Kaggle. 2018b. “NBA Enhanced Box Scores and Standings.” <a href="https://www.kaggle.com/pablote/nba-enhanced-stats">https://www.kaggle.com/pablote/nba-enhanced-stats</a>.</p>
</div>
<div id="ref-Kolata2009">
<p>Kolata, Gina. 2009. “Picture Emerging on Genetic Risks of Ivf.” <em>The New York Times</em>.</p>
</div>
<div id="ref-Martinsen2009">
<p>Martinsen, M, S Bratland-Sanda, A K Eriksson, and J Sundgot-Borgen. 2009. “Dieting to Win or to Be Thin? A Study of Dieting and Disordered Eating Among Adolescent Elite Athletes and Non-Athlete Controls.” <em>British Journal of Sports Medicine</em> 44 (1): 70–76. <a href="http://bjsm.bmj.com/content/44/1/70">http://bjsm.bmj.com/content/44/1/70</a>.</p>
</div>
<div id="ref-Nafstad1999">
<p>Nafstad, Per, Jorgen A. Hagen, Leif Oie, Per Magnus, and Jouni J. K. Jaakkola. 1999. “Day Care Centers and Respiratory Health.” <em>Pediatrics</em> 103 (4): 753–58. <a href="http://pediatrics.aappublications.org/content/103/4/753">http://pediatrics.aappublications.org/content/103/4/753</a>.</p>
</div>
<div id="ref-Ramsey2002">
<p>Ramsey, Fred, and Daniel Schafer. 2002. <em>The Statistical Sleuth: A Course in Methods of Data Analysis</em>. 2nd ed. Boston, Massachusetts: Brooks/Cole Cengage.</p>
</div>
<div id="ref-Roskes2011">
<p>Roskes, Marieke, Daniel Sligte, Shaul Shalvi, and Carsten K. W. De Dreu. 2011. “The Right Side? Under Time Pressure, Approach Motivation Leads to Right-Oriented Bias.” <em>Psychology Science</em> 22 (11): 1403–7. <a href="https://doi.org/10.1177/0956797611418677">https://doi.org/10.1177/0956797611418677</a>.</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="ch-glms.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="ch-corrdata.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook/js/app.min.js"></script>
<script src="libs/gitbook/js/lunr.js"></script>
<script src="libs/gitbook/js/clipboard.min.js"></script>
<script src="libs/gitbook/js/plugin-search.js"></script>
<script src="libs/gitbook/js/plugin-sharing.js"></script>
<script src="libs/gitbook/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook/js/plugin-bookdown.js"></script>
<script src="libs/gitbook/js/jquery.highlight.js"></script>
<script src="libs/gitbook/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
